(function (global) {
  'use strict';
  var v2=global.GugudanV2,validators=v2.validators=v2.validators||{};
  function validateCurrencyData(currency){var errors=[];['coins','normalTickets','premiumTickets'].forEach(function(key){if(!Number.isInteger(currency&&currency[key])||currency[key]<0)errors.push(key);});return{valid:!errors.length,errors:errors};}
  function validateCollectionData(collection){var errors=[],ids=(collection&&collection.ownedCatIds)||[],known=[].concat(v2.baseCats||[],v2.seasonCats||[]).map(function(cat){return cat.id;});if(new Set(ids).size!==ids.length)errors.push('duplicate_owned_ids');ids.forEach(function(id){if(known.indexOf(id)<0)errors.push('unknown_cat:'+id);});Object.keys((collection&&collection.duplicateCounts)||{}).forEach(function(id){if(collection.duplicateCounts[id]<0)errors.push('negative_duplicate:'+id);});['normal','rare','hero','legendary'].forEach(function(rarity){if(!Number.isInteger(collection&&collection.catFragments&&collection.catFragments[rarity])||collection.catFragments[rarity]<0)errors.push('fragment:'+rarity);});return{valid:!errors.length,errors:errors};}
  function validateSelectedCat(save){var known=[].concat(v2.baseCats||[],v2.seasonCats||[]).some(function(cat){return cat.id===save.profile.selectedCatId;}),owned=save.collection.ownedCatIds.indexOf(save.profile.selectedCatId)>=0;return{valid:known&&owned,errors:known&&owned?[]:['selected_cat']};}
  function validateRewardHistory(history){var errors=[];if(!history||!Array.isArray(history.rewardedSessionIds)||!Array.isArray(history.firstClearStageIds)||!history.rewardedStarMilestones)errors.push('shape');else Object.keys(history.rewardedStarMilestones).forEach(function(id){var star=history.rewardedStarMilestones[id];if(star<0||star>3)errors.push(id);});return{valid:!errors.length,errors:errors};}
  Object.assign(validators,{validateRewardConfig:function(){return v2.rewardService.validateRewardConfig(v2.rewardConfig);},validateCardPackConfig:function(){return v2.cardPackService.validateCardPackConfig();},validateCollectionData:validateCollectionData,validateCurrencyData:validateCurrencyData,validateCatSkillData:function(){return v2.skillEngine.validateCatSkillData();},validateSelectedCat:validateSelectedCat,validateSkillSession:function(){return v2.skillEngine.validateSkillSession();},validateRewardHistory:validateRewardHistory});
})(window);
