(function (global) {
  'use strict';
  global.GugudanV2 = global.GugudanV2 || {};
  function duplicates(values) { return values.filter(function (value, index) { return values.indexOf(value) !== index; }); }
  function validateCats(cats) {
    var errors = [], allowed = ['normal', 'rare', 'hero', 'legendary'], skills = [];
    duplicates(cats.map(function (cat) { return cat.id; })).forEach(function (id) { errors.push('중복 고양이 ID: ' + id); });
    cats.forEach(function (cat) { if (!cat.id || !cat.displayName || !cat.image) errors.push('필수 필드 누락: ' + (cat.id || 'unknown')); if (allowed.indexOf(cat.rarity) < 0) errors.push('잘못된 등급: ' + cat.id); if ((cat.rarity === 'normal' || cat.rarity === 'rare') && cat.skill) errors.push('일반/희귀 스킬 금지: ' + cat.id); if ((cat.rarity === 'hero' || cat.rarity === 'legendary') && (!cat.skill || !cat.skill.id)) errors.push('영웅/전설 스킬 누락: ' + cat.id); if (cat.skill) skills.push(cat.skill.id); });
    duplicates(skills).forEach(function (id) { errors.push('중복 스킬 ID: ' + id); }); return errors;
  }
  function validateSeasons(seasons, cats) { var errors = [], catIds = cats.map(function (cat) { return cat.id; }), policies = ['permanent', 'unavailable', 'limited_return', 'special_shop']; duplicates(seasons.map(function (season) { return season.id; })).forEach(function (id) { errors.push('중복 시즌 ID: ' + id); }); seasons.forEach(function (season) { if (season.startAt && season.endAt && new Date(season.startAt) > new Date(season.endAt)) errors.push('잘못된 시즌 날짜: ' + season.id); (season.catIds || []).forEach(function (id) { if (catIds.indexOf(id) < 0) errors.push('없는 고양이 참조: ' + id); }); if (policies.indexOf(season.afterSeasonPolicy) < 0) errors.push('잘못된 종료 정책: ' + season.id); }); return errors; }
  function validateSounds(config) { var errors = [], sounds = [].concat(config.correct || [], config.wrong || [], config.skills || [], config.boss || [], config.reward || []); duplicates(sounds.map(function (sound) { return sound.id; })).forEach(function (id) { errors.push('중복 사운드 ID: ' + id); }); sounds.forEach(function (sound) { if (!/\.(mp3|wav|ogg|m4a)$/i.test(sound.path || '')) errors.push('지원하지 않는 사운드 경로: ' + sound.id); }); return errors; }
  function validateAdminConfig(config) { var errors = []; if (config && config.answerCount != null && [2, 4, 8].indexOf(config.answerCount) < 0) errors.push('보기 개수는 2, 4, 8만 지원합니다.'); return errors; }
  function validateAll() { var baseCats = global.GugudanV2.baseCats || [], cats = [].concat(baseCats,global.GugudanV2.seasonCats||[]), seasons = global.GugudanV2.seasons || [], sounds = global.GugudanV2.soundConfig || {}; var errors = validateCats(cats).concat(validateSeasons(seasons, cats), validateSounds(sounds)); if (errors.length) console.warn('[V2 validation]', errors); else console.info('[V2 validation] 기반 데이터 검증 통과'); return { valid: errors.length === 0, errors: errors, counts: baseCats.reduce(function (result, cat) { result[cat.rarity] = (result[cat.rarity] || 0) + 1; return result; }, {}) }; }
  function validateWorldData(worlds) { var errors = [], ids = worlds.map(function (world) { return world.id; }), orders = worlds.map(function (world) { return world.order; }); duplicates(ids).forEach(function (id) { errors.push('중복 월드 ID: ' + id); }); duplicates(orders).forEach(function (order) { errors.push('중복 월드 순서: ' + order); }); worlds.forEach(function (world) { (world.multiplicationTables || []).forEach(function (table) { if (table < 2 || table > 9) errors.push('잘못된 출제 단: ' + world.id); }); }); return errors; }
  function validateStageData(stages, worlds) { var errors = [], ids = stages.map(function (stage) { return stage.id; }), worldIds = worlds.map(function (world) { return world.id; }); duplicates(ids).forEach(function (id) { errors.push('중복 스테이지 ID: ' + id); }); stages.forEach(function (stage) { if (worldIds.indexOf(stage.worldId) < 0) errors.push('없는 월드 참조: ' + stage.id); if (!stage.rules || stage.rules.questionCount < 1 || [4,6,8].indexOf(stage.rules.answerOptionCount) < 0) errors.push('잘못된 스테이지 규칙: ' + stage.id); if (!stage.starConditions || stage.starConditions.length !== 3) errors.push('별 조건 오류: ' + stage.id); if ((stage.type === 'midBoss' || stage.type === 'boss') && !stage.boss) errors.push('보스 데이터 누락: ' + stage.id); }); return errors; }
  function validateActiveGameModes(config) { var active = Object.keys(config.modes).filter(function (mode) { return config.modes[mode].enabled; }).sort(), expected = ['adventure','classic','timeAttack']; return { valid: JSON.stringify(active) === JSON.stringify(expected), active: active, errors: JSON.stringify(active) === JSON.stringify(expected) ? [] : ['활성 모드는 classic, timeAttack, adventure여야 합니다.'] }; }
  global.GugudanV2.validators = { validateCats: validateCats, validateSeasons: validateSeasons, validateSounds: validateSounds, validateAdminConfig: validateAdminConfig, validateWorldData: validateWorldData, validateStageData: validateStageData, validateActiveGameModes: validateActiveGameModes, validateAll: validateAll };
})(window);
