(function (root, factory) {
  var controller = factory(root && root.GugudanV2);
  if (typeof module !== 'undefined' && module.exports) module.exports = controller;
  if (root) { root.GugudanV2 = root.GugudanV2 || {}; root.GugudanV2.adminModeController = controller; }
})(typeof window !== 'undefined' ? window : null, function (v2) {
  'use strict';
  var state = { context: null, target: null, selectedUids: {}, pending: null, lastFocus: null, processing: false, users: [], searchResult: null, serverSearchResults: [], searchActive: false, cursor: null, hasMore: false, loadingDirectory: false };
  var labels = { coins: '코인', normalTickets: '일반 뽑기권', premiumTickets: '고급 뽑기권' };
  function svc() { return (typeof window !== 'undefined' && window.GugudanV2) || v2 || {}; }
  function validation() { return svc().adminValidationService; }
  function firestore() { return svc().adminFirestoreService; }
  function rootEl() { return typeof document === 'undefined' ? null : document.getElementById('admin-mode-root'); }
  function isAdmin(auth) { return Boolean(validation() && validation().isCurrentUserAdmin(auth)); }
  function esc(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, function (c) { return ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[c]; }); }
  function shortUid(uid) { return uid && uid.length > 10 ? uid.slice(0, 6) + '…' + uid.slice(-4) : (uid || '-'); }
  function userCurrency(user) { return user.currency || { coins: user.coins || 0, normalTickets: user.normalTickets || 0, premiumTickets: user.premiumTickets || 0 }; }
  function rarityCounts(user) { var source=user&&user.ownedCatRarityCounts||{}, result={legendary:0,hero:0,rare:0,normal:0};Object.keys(result).forEach(function(rarity){result[rarity]=Number.isInteger(source[rarity])&&source[rarity]>=0?source[rarity]:0;});return result; }
  function catCountMarkup(user) { var counts=rarityCounts(user),detail='전설 '+counts.legendary+' · 영웅 '+counts.hero+' · 희귀 '+counts.rare+' · 일반 '+counts.normal;return '<div class="admin-cat-count-cell"><strong>'+esc(Number.isInteger(user.ownedCatCount)&&user.ownedCatCount>=0?user.ownedCatCount:0)+'종</strong><span title="'+esc(detail)+'">'+esc(detail)+'</span></div>'; }
  function userForTarget(user) { var c = userCurrency(user); return { uid:user.uid, loginId:user.loginId || '', nickname:user.nickname || '', level:user.level || 0, coins:c.coins || 0, normalTickets:c.normalTickets || 0, premiumTickets:c.premiumTickets || 0, ownedCatCount:user.ownedCatCount || 0 }; }
  function errorCode(error) { return error && (error.code || error.message) || ''; }
  function messageFor(error, area) {
    var code = errorCode(error);
    var messages = { 'permission-denied': area === 'history' ? '최근 지급 기록을 불러올 권한이 없습니다. 관리자 보안 규칙 적용 상태를 확인해 주세요.' : '사용자 조회 권한이 없습니다. 새 관리자 보안 규칙이 아직 적용되지 않았을 수 있습니다.', permission_denied: '사용자 조회 권한이 없습니다. 새 관리자 보안 규칙이 아직 적용되지 않았을 수 있습니다.', 'not-found':'사용자를 찾을 수 없습니다.', target_user_not_found:'사용자를 찾을 수 없습니다.', duplicate_login_id:'같은 로그인 ID를 사용하는 계정이 여러 개 있어 대상을 확정할 수 없습니다.', unavailable:'네트워크 연결을 확인한 뒤 다시 시도해 주세요.', network:'네트워크 연결을 확인한 뒤 다시 시도해 주세요.', admin_forbidden:'관리자만 이용할 수 있습니다.', admin_auth_required:'로그인이 필요합니다.', invalid_amount:'지급 수량을 확인해 주세요.', cat_grants_disabled:'고양이 지급은 현재 지원하지 않습니다.', action_id_conflict:'같은 작업 번호가 다른 지급 요청에 사용되었습니다.' };
    return messages[code] || '처리 중 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.';
  }
  function createActionId() { if (typeof crypto !== 'undefined' && crypto.randomUUID) return crypto.randomUUID(); var bytes = typeof crypto !== 'undefined' && crypto.getRandomValues ? crypto.getRandomValues(new Uint32Array(4)) : [Math.random()*0xffffffff,Math.random()*0xffffffff,Math.random()*0xffffffff,Math.random()*0xffffffff]; return Array.prototype.map.call(bytes,function (v) { return Math.floor(v).toString(16).padStart(8,'0'); }).join('-'); }
  function formatKst(value) { var date=value&&typeof value.toDate==='function'?value.toDate():(value instanceof Date?value:(value?new Date(value):null)); if(!date||isNaN(date.getTime())) return '처리 시간 기록 중'; return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'short',timeStyle:'short'}).format(date); }
  function setStatus(area, text, kind) { var node=rootEl()&&rootEl().querySelector('[data-admin-'+area+'-status]'); if(node){node.textContent=text||'';node.className='admin-mode__message'+(kind?' is-'+kind:'');} }
  function renderUserCard(user) { var target = state.target && state.target.uid === user.uid, c=userCurrency(user); return '<article class="admin-user-card'+(target?' is-selected':'')+'" data-admin-user="'+esc(user.uid)+'"><div><strong>'+esc(user.nickname||'게임 닉네임 없음')+'</strong><span>게임 닉네임: '+esc(user.nickname||'없음')+'</span><span>로그인 ID: '+esc(user.loginId||'없음')+'</span><span class="admin-user-card__uid">UID: <code data-full-uid="'+esc(user.uid)+'">'+esc(shortUid(user.uid))+'</code><button type="button" data-copy-uid="'+esc(user.uid)+'">복사</button></span></div><p>Lv.'+esc(user.level||0)+' · 코인 '+esc(c.coins||0)+' · 일반권 '+esc(c.normalTickets||0)+' · 고급권 '+esc(c.premiumTickets||0)+' · 고양이 '+esc(user.ownedCatCount||0)+'종</p><button class="btn admin-select-user-button" type="button" data-select-user="'+esc(user.uid)+'">'+(target?'선택됨':'이 사용자 선택')+'</button></article>'; }
  function renderUserRow(user) { var selected=Boolean(state.selectedUids[user.uid]),c=userCurrency(user);return '<tr class="admin-user-row'+(selected?' is-selected':'')+'" data-admin-user="'+esc(user.uid)+'"><td class="admin-user-table__select" data-label="선택"><input aria-label="'+esc(user.nickname||user.uid)+' 선택" type="checkbox" data-user-check="'+esc(user.uid)+'"'+(selected?' checked':'')+'></td><td class="admin-user-table__text" data-label="게임 닉네임" title="'+esc(user.nickname||'-')+'">'+esc(user.nickname||'-')+'</td><td class="admin-user-table__text" data-label="로그인 ID" title="'+esc(user.loginId||'-')+'">'+esc(user.loginId||'-')+'</td><td class="admin-user-table__uid" data-label="UID"><div class="admin-user-uid-cell"><span class="admin-user-uid-value" title="'+esc(user.uid)+'">'+esc(shortUid(user.uid))+'</span><button class="admin-button--compact" type="button" data-copy-uid="'+esc(user.uid)+'" aria-label="UID 복사">복사</button></div></td><td class="admin-number" data-label="레벨">'+esc(user.level||'-')+'</td><td class="admin-number" data-label="코인">'+esc(c.coins||0)+'</td><td class="admin-number" data-label="일반권">'+esc(c.normalTickets||0)+'</td><td class="admin-number" data-label="고급권">'+esc(c.premiumTickets||0)+'</td><td class="admin-user-table__cats" data-label="고양이">'+catCountMarkup(user)+'</td></tr>'; }
  function renderUserCard(user) { return renderUserRow(user); }
  function userTable(users) { var rows=users.length?users.map(renderUserRow).join(''):'<tr class="admin-user-table__empty"><td colspan="9">일치하는 사용자를 찾지 못했습니다.</td></tr>';return '<div class="admin-table-wrap"><table class="admin-user-table"><colgroup><col class="admin-col-select"><col class="admin-col-nickname"><col class="admin-col-login"><col class="admin-col-uid"><col class="admin-col-level"><col class="admin-col-coins"><col class="admin-col-normal-ticket"><col class="admin-col-premium-ticket"><col class="admin-col-cats"></colgroup><thead><tr><th scope="col" class="admin-user-column-select">선택<input type="checkbox" data-select-visible aria-label="현재 표시 사용자 전체 선택"></th><th scope="col">게임 닉네임</th><th scope="col">로그인 ID</th><th scope="col" class="admin-user-column-uid">UID</th><th scope="col" class="admin-number">레벨</th><th scope="col" class="admin-number">코인</th><th scope="col" class="admin-number">일반권</th><th scope="col" class="admin-number">고급권</th><th scope="col" class="admin-number">고양이</th></tr></thead><tbody>'+rows+'</tbody></table></div>'; }
  function renderScreen() { var root=rootEl(); if(!root)return; root.innerHTML='<main class="admin-mode admin-mode-shell" aria-labelledby="admin-mode-title"><header><h1 id="admin-mode-title">🛠️ 관리자 모드</h1><p>게임 닉네임 · 로그인 ID · UID를 확인한 뒤 지급 대상을 선택하세요.</p></header><section class="admin-mode__panel"><div class="admin-section-heading"><h2>전체 사용자</h2><button class="admin-button--compact" type="button" data-directory-refresh>새로고침</button></div><form class="admin-unified-search" data-admin-search><label class="sr-only" for="admin-user-query">게임 닉네임, 로그인 ID 또는 UID 검색</label><input id="admin-user-query" name="query" autocomplete="off" placeholder="게임 닉네임, 로그인 ID 또는 UID 검색"><button class="admin-button--compact admin-search-button" type="submit">검색</button><button class="admin-button--compact" type="button" data-search-reset>초기화</button></form><p class="admin-mode__message" data-admin-search-status aria-live="polite"></p><div data-admin-directory></div><div class="admin-directory-actions"><button class="admin-button--compact" type="button" data-directory-more hidden>사용자 더 보기</button></div></section><section class="admin-mode__panel"><h2>재화 지급</h2><p class="admin-mode__quiet" data-target-hint>먼저 사용자 목록이나 검색 결과에서 지급 대상을 선택해 주세요.</p><div data-admin-target></div><p class="admin-mode__quiet">고양이 지급은 현재 지원하지 않습니다.</p><form data-admin-grant><label>재화<select name="grantType" disabled><option value="coins">코인</option><option value="normalTickets">일반 뽑기권</option><option value="premiumTickets">고급 뽑기권</option></select></label><label>수량<input name="amount" type="number" min="1" step="1" disabled></label><label>메모 (선택)<input name="note" maxlength="100" disabled></label><button class="admin-button--compact admin-grant-review-button" type="submit" disabled>지급 전 확인</button></form><p class="admin-mode__message" data-admin-grant-status aria-live="polite"></p></section><section class="admin-mode__panel"><h2>최근 관리자 지급</h2><p class="admin-mode__message" data-admin-history-status aria-live="polite"></p><div class="admin-table-wrap"><table class="admin-history-table"><thead><tr><th>일시</th><th>대상 닉네임</th><th>로그인 ID</th><th>지급 항목</th><th>수량</th><th>사유</th><th>상태</th></tr></thead><tbody data-admin-history></tbody></table></div></section><button class="admin-button--compact" type="button" data-admin-back>로비로 돌아가기</button></main>'; bindScreen(); loadDirectory(true); loadHistory(); }
  function bindScreen() { var root=rootEl(), searchForm=root.querySelector('[data-admin-search]'); searchForm.addEventListener('submit',search); searchForm.query.addEventListener('input',function(){if(isBatchProcessing())return;state.searchActive=false;state.serverSearchResults=[];renderDirectory();}); root.querySelector('[data-search-reset]').addEventListener('click',resetSearch); root.querySelector('[data-directory-refresh]').addEventListener('click',function(){loadDirectory(true);}); root.querySelector('[data-directory-more]').addEventListener('click',function(){loadDirectory(false);}); root.querySelector('[data-admin-grant]').addEventListener('submit',prepareGrant); root.querySelector('[data-admin-back]').addEventListener('click',backToLobby); root.addEventListener('click',handleCardAction); root.addEventListener('change',handleSelectionChange); }
  function handleSelectionChange(event) { var check=event.target.closest('[data-user-check]'), all=event.target.closest('[data-select-visible]'); if(check){setSelected(check.dataset.userCheck,check.checked);return;} if(all){(state.searchActive?state.serverSearchResults:visibleUsers()).forEach(function(user){setSelected(user.uid,all.checked,true);});renderDirectory();} }
  function visibleUsers(){var query=(rootEl().querySelector('[data-admin-search] input')||{}).value||'';query=query.trim().toLowerCase();return state.users.filter(function(user){return !query||[user.nickname,user.loginId,user.uid].some(function(value){return String(value||'').toLowerCase().indexOf(query)>=0;});});}
  function setSelected(uid, selected, silent){if(selected&&!state.selectedUids[uid]&&Object.keys(state.selectedUids).length>=30){setStatus('grant','한 번에 최대 30명까지 지급할 수 있습니다.','error');return;}if(selected)state.selectedUids[uid]=true;else delete state.selectedUids[uid];if(!silent)renderDirectory();}
  function renderDirectory() { var node=rootEl()&&rootEl().querySelector('[data-admin-directory]'), more=rootEl()&&rootEl().querySelector('[data-directory-more]'), users=state.searchActive?state.serverSearchResults:visibleUsers(); if(!node)return; node.innerHTML=userTable(users); var all=node.querySelector('[data-select-visible]');if(all){var count=users.filter(function(u){return state.selectedUids[u.uid];}).length;all.checked=Boolean(users.length&&count===users.length);all.indeterminate=count>0&&count<users.length;} if(more)more.hidden=state.searchActive||!state.hasMore; renderTarget(); }
  function loadDirectory(reset) { if(!authorize()||state.loadingDirectory)return; if(reset){state.users=[];state.cursor=null;state.hasMore=false;} state.loadingDirectory=true;var more=rootEl().querySelector('[data-directory-more]');if(more){more.disabled=true;more.textContent='불러오는 중…';}setStatus('search',''); Promise.resolve(firestore().listAdminUsersPage({auth:state.context.auth,db:state.context.db,firebase:state.context.firebase,pageSize:30,cursor:state.cursor})).then(function(page){var known={};state.users.forEach(function(user){known[user.uid]=true;});(page.users||[]).forEach(function(user){if(!known[user.uid]){known[user.uid]=true;state.users.push(user);}});state.cursor=page.cursor;state.hasMore=Boolean(page.hasMore);renderDirectory();}).catch(function(error){setStatus('search',messageFor(error,'directory'),'error');}).finally(function(){state.loadingDirectory=false;if(more){more.disabled=false;more.textContent='사용자 더 보기';}}); }
  function search(event) { event.preventDefault();if(!authorize()||isBatchProcessing())return;var form=event.currentTarget,button=form.querySelector('[type="submit"]'),query=form.query.value.trim();if(!query){resetSearch();return;}button.disabled=true;button.textContent='검색 중…';setStatus('search','');Promise.resolve(firestore().searchAdminUsersExact(query,state.context)).then(function(users){state.serverSearchResults=users||[];state.searchResult=state.serverSearchResults[0]||null;state.searchActive=true;renderDirectory();}).catch(function(error){state.serverSearchResults=[];state.searchResult=null;state.searchActive=true;renderDirectory();setStatus('search',messageFor(error,'search'),'error');}).finally(function(){button.disabled=false;button.textContent='검색';}); }
  function resetSearch(){ if(isBatchProcessing())return;var form=rootEl()&&rootEl().querySelector('[data-admin-search]');if(form)form.query.value='';state.searchActive=false;state.serverSearchResults=[];state.searchResult=null;setStatus('search','');renderDirectory(); }
  function handleCardAction(event) { var select=event.target.closest('[data-select-user]'), copy=event.target.closest('[data-copy-uid]');if(select){var uid=select.dataset.selectUser,user=state.users.filter(function(item){return item.uid===uid;})[0]||((state.searchResult&&state.searchResult.uid===uid)?state.searchResult:null);if(user)selectUser(user);return;}if(copy)copyUid(copy.dataset.copyUid,copy); }
  function copyUid(uid,button) { var done=function(){button.textContent='복사됨';setTimeout(function(){button.textContent='복사';},1200);};if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(uid).then(done);return;}var fallback=document.createElement('textarea');fallback.value=uid;fallback.setAttribute('aria-hidden','true');fallback.tabIndex=-1;fallback.style.cssText='position:fixed;left:-9999px;top:auto;width:1px;height:1px;opacity:0;';document.body.appendChild(fallback);fallback.focus();fallback.select();try{document.execCommand('copy');done();}finally{fallback.remove();} }
  function selectUser(user) { state.target=userForTarget(user);state.pending=null;closeConfirm();var form=rootEl().querySelector('[data-admin-grant]');form.reset();form.querySelectorAll('input,select,button').forEach(function(node){node.disabled=false;});setStatus('grant','');renderDirectory();renderTarget(); }
  function renderTarget() { var node=rootEl()&&rootEl().querySelector('[data-admin-target]'),hint=rootEl()&&rootEl().querySelector('[data-target-hint]');if(!node)return;if(!state.target){node.replaceChildren();if(hint)hint.hidden=false;return;}var t=state.target;node.innerHTML='<div class="admin-target-card"><h3>지급 대상</h3><p>게임 닉네임: <strong>'+esc(t.nickname||'없음')+'</strong></p><p>로그인 ID: <strong>'+esc(t.loginId||'없음')+'</strong></p><p>UID: <code>'+esc(shortUid(t.uid))+'</code></p><p>현재 코인 '+esc(t.coins)+' · 일반권 '+esc(t.normalTickets)+' · 고급권 '+esc(t.premiumTickets)+'</p></div>';if(hint)hint.hidden=true; }
  function prepareGrant(event) {event.preventDefault();if(!authorize()||!state.target||state.processing)return;var form=event.currentTarget,type=form.grantType.value,amount=Number(form.amount.value),limit=validation().RESOURCE_LIMITS[type],note=form.note.value.trim();if(!Number.isInteger(amount)||amount<1||amount>limit){setStatus('grant','수량은 1부터 '+limit.toLocaleString('ko-KR')+'까지 입력해 주세요.','error');return;}if(!state.pending||state.pending.targetUid!==state.target.uid||state.pending.grantType!==type||state.pending.amount!==amount||state.pending.note!==note)state.pending={targetUid:state.target.uid,grantType:type,amount:amount,note:note,actionId:null};openConfirm();}
  function openConfirm(){var root=rootEl(),p=state.pending,t=state.target,before=t[p.grantType],after=before+p.amount;state.lastFocus=document.activeElement;var modal=document.createElement('div');modal.className='admin-confirm-modal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.innerHTML='<div class="admin-confirm-modal__panel"><h2>지급을 확인할까요?</h2><p>게임 닉네임: <strong>'+esc(t.nickname||'없음')+'</strong><br>로그인 ID: '+esc(t.loginId||'없음')+'</p><p>'+esc(labels[p.grantType])+' '+esc(p.amount)+'개<br>지급 전 '+esc(before)+' → 지급 후 '+esc(after)+'</p>'+(p.note?'<p class="admin-confirm-modal__note">메모: '+esc(p.note)+'</p>':'')+'<div><button class="btn" type="button" data-admin-cancel>취소</button><button class="btn btn-success" type="button" data-admin-confirm>지급하기</button></div></div>';root.appendChild(modal);modal.querySelector('[data-admin-cancel]').addEventListener('click',closeConfirm);modal.querySelector('[data-admin-confirm]').addEventListener('click',confirmGrant);modal.addEventListener('keydown',function(e){if(e.key==='Escape'&&!state.processing){e.preventDefault();closeConfirm();}});modal.querySelector('[data-admin-confirm]').focus();}
  function closeConfirm(){var modal=rootEl()&&rootEl().querySelector('.admin-confirm-modal');if(modal)modal.remove();if(state.lastFocus&&state.lastFocus.focus)state.lastFocus.focus();}
  function confirmGrant(){if(!authorize()||!state.pending||state.processing)return;state.processing=true;var modal=rootEl().querySelector('.admin-confirm-modal'),button=modal.querySelector('[data-admin-confirm]');button.disabled=true;if(!state.pending.actionId)state.pending.actionId=createActionId();var request=Object.assign({},state.pending);Promise.resolve(firestore().grantAdminResource(request,state.context)).then(function(result){state.processing=false;closeConfirm();state.pending=null;state.target[result.type]=result.after;state.users.forEach(function(user){if(user.uid===state.target.uid)userCurrency(user)[result.type]=result.after;});renderDirectory();renderTarget();setStatus('grant',result.idempotentReplay?'이미 처리된 작업 번호입니다. 추가 지급은 이루어지지 않았습니다.':'지급이 완료되었습니다.','success');loadHistory();}).catch(function(error){state.processing=false;button.disabled=false;if(/unavailable|network|deadline|timeout/i.test(errorCode(error))){setStatus('grant','네트워크 연결을 확인한 뒤 같은 작업 번호로 다시 시도해 주세요.','error');return;}state.pending=null;closeConfirm();setStatus('grant',messageFor(error,'grant'),'error');});}
  function loadHistory(){if(!authorize(false))return;Promise.resolve(firestore().listRecentAdminActions(20,state.context)).then(function(actions){var node=rootEl()&&rootEl().querySelector('[data-admin-history]');if(node)node.innerHTML=actions.length?actions.map(function(a){return '<tr><td>'+esc(formatKst(a.createdAt))+'</td><td>'+esc(a.targetNickname||'-')+'</td><td>'+esc(a.targetLoginId||'-')+'</td><td>'+esc(labels[a.type]||a.type)+'</td><td class="admin-number">'+esc(a.amount||0)+'</td><td class="admin-note" title="'+esc(a.note||'')+'">'+esc(a.note||'-')+'</td><td>'+esc(a.status||'처리됨')+'</td></tr>';}).join(''):'<tr><td class="admin-mode__empty" colspan="7">아직 지급 이력이 없습니다.</td></tr>';}).catch(function(error){setStatus('history',messageFor(error,'history'),'error');});}
  function authorize(returnLobby){if(isAdmin(state.context&&state.context.auth))return true;if(returnLobby!==false){if(typeof window!=='undefined'&&window.alert)window.alert('관리자만 이용할 수 있습니다.');clear();if(state.context&&state.context.showLobby)state.context.showLobby();}return false;}
  function open(context){state.context=context||state.context;if(!authorize())return false;renderScreen();if(state.context.showScreen)state.context.showScreen('admin-screen');return true;}
  function renderMenu(context){if(context)state.context=Object.assign({},state.context||{},context);var slot=typeof document!=='undefined'&&document.getElementById('admin-menu-slot');if(!slot)return;slot.replaceChildren();if(!isAdmin(state.context&&state.context.auth))return;var button=document.createElement('button');button.type='button';button.className='admin-menu-button';button.textContent='🛠️ 관리자';button.addEventListener('click',function(){(state.context.open||open)(state.context);});slot.appendChild(button);}
  function handleAuthStateChanged(){renderMenu();if(!isAdmin(state.context&&state.context.auth))clear();}
  function backToLobby(){clear();if(state.context&&state.context.showLobby)state.context.showLobby();}
  function clear(){state.target=null;state.pending=null;state.processing=false;state.activeBatch=null;state.batchUiState=null;state.selectedUids={};state.users=[];state.searchResult=null;state.serverSearchResults=[];state.searchActive=false;state.cursor=null;state.hasMore=false;var root=rootEl();if(root)root.replaceChildren();var slot=typeof document!=='undefined'&&document.getElementById('admin-menu-slot');if(slot)slot.replaceChildren();}
  /* Batch grants intentionally replace the legacy single-target confirmation path above. */
  function batchService(){ return svc().adminBatchGrantService; }
  function isBatchProcessing(){ return state.batchUiState==='processing'||state.batchUiState==='retrying'; }
  function selectedUserSnapshot(){ var seen={}, ordered=(state.users||[]).concat(state.serverSearchResults||[]); return ordered.filter(function(user){ if(!user||!state.selectedUids[user.uid]||seen[user.uid])return false;seen[user.uid]=true;return true; }).map(function(user){return {uid:user.uid,nickname:user.nickname||'',loginId:user.loginId||'',currency:Object.assign({},userCurrency(user))};}).slice(0,30); }
  function renderBatchTarget(){ var root=rootEl(),node=root&&root.querySelector('[data-admin-target]'),hint=root&&root.querySelector('[data-target-hint]'),form=root&&root.querySelector('[data-admin-grant]'),users=selectedUserSnapshot();if(!node)return;if(!users.length){node.replaceChildren();if(hint)hint.hidden=false;if(form)form.querySelectorAll('input,select,button').forEach(function(control){control.disabled=true;});return;}node.innerHTML='<div class="admin-target-card"><h3>지급 대상 '+esc(users.length)+'명</h3><p>'+users.map(function(user){return esc(user.nickname||'게임 닉네임 없음')+' · '+esc(user.loginId||'로그인 ID 없음')+' · <code>'+esc(shortUid(user.uid))+'</code>';}).join('<br>')+'</p></div>';if(hint)hint.hidden=true;if(form)form.querySelectorAll('input,select,button').forEach(function(control){control.disabled=isBatchProcessing();}); }
  function renderTarget(){ renderBatchTarget(); }
  function closeBatchModal(){ var modal=rootEl()&&rootEl().querySelector('.admin-confirm-modal');if(modal)modal.remove();if(state.lastFocus&&state.lastFocus.focus)state.lastFocus.focus(); }
  function batchEntries(batch){ return batch&&batch.entries?Object.keys(batch.entries).map(function(uid){return batch.entries[uid];}):[]; }
  function batchCounts(batch){ var counts={total:0,success:0,replay:0,failed:0,uncertain:0,processing:0};batchEntries(batch).forEach(function(entry){counts.total++;if(counts[entry.status]!==undefined)counts[entry.status]++;});return counts; }
  function batchResultMessage(entry){ if(entry.status==='success')return '지급 완료';if(entry.status==='replay')return '이미 처리됨';if(entry.status==='uncertain')return '결과 확인 필요 — 같은 작업 번호로 다시 시도할 수 있습니다.';return entry.errorCode?messageFor({code:entry.errorCode},'grant'):'지급하지 못했습니다.'; }
  function setBatchControls(disabled){ var shell=rootEl()&&rootEl().querySelector('.admin-mode');if(!shell)return;shell.setAttribute('aria-busy',disabled?'true':'false');shell.querySelectorAll('button,input,select,textarea').forEach(function(node){node.disabled=disabled;}); }
  function openBatchConfirmModal(){ var root=rootEl(),batch=state.activeBatch,users=batchEntries(batch);if(!root||!batch)return;state.lastFocus=document.activeElement;closeBatchModal();var modal=document.createElement('div');modal.className='admin-confirm-modal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.innerHTML='<div class="admin-confirm-modal__panel"><h2>일괄 지급을 확인할까요?</h2><p><strong>'+esc(users.length)+'명</strong>에게 '+esc(labels[batch.resourceType])+' '+esc(batch.amount)+'개를 지급합니다.</p>'+(batch.note?'<p class="admin-confirm-modal__note">메모: '+esc(batch.note)+'</p>':'')+'<ul class="admin-batch-target-list">'+users.map(function(entry){return '<li>'+esc(entry.user.nickname||'게임 닉네임 없음')+' · '+esc(entry.user.loginId||'로그인 ID 없음')+' · <code>'+esc(shortUid(entry.uid))+'</code></li>';}).join('')+'</ul><div><button class="btn" type="button" data-admin-cancel>취소</button><button class="btn btn-success" type="button" data-admin-confirm>'+esc(users.length)+'명에게 지급</button></div></div>';root.appendChild(modal);modal.querySelector('[data-admin-cancel]').addEventListener('click',function(){state.activeBatch=null;closeBatchModal();});modal.querySelector('[data-admin-confirm]').addEventListener('click',startConfirmedBatchGrant);modal.addEventListener('keydown',function(event){if(event.key==='Escape'){event.preventDefault();}});modal.querySelector('[data-admin-confirm]').focus(); }
  function prepareGrant(event){ event.preventDefault();if(!authorize()||isBatchProcessing())return;var users=selectedUserSnapshot(),form=event.currentTarget,type=form.grantType.value,amount=Number(form.amount.value),limit=validation().RESOURCE_LIMITS[type],note=form.note.value.trim();if(!users.length){setStatus('grant','지급할 사용자를 1명 이상 선택해 주세요.','error');return;}if(users.length>30){setStatus('grant','한 번에 최대 30명까지 지급할 수 있습니다.','error');return;}if(!Number.isInteger(amount)||amount<1||amount>limit){setStatus('grant','수량은 1부터 '+limit.toLocaleString('ko-KR')+'까지 입력해 주세요.','error');return;}if(!batchService()||typeof batchService().createBatch!=='function'){setStatus('grant','일괄 지급 서비스를 불러오지 못했습니다.','error');return;}state.activeBatch=batchService().createBatch(users,{resourceType:type,amount:amount,note:note},validation().validateActionId);state.batchUiState='confirm';openBatchConfirmModal(); }
  function renderBatchProgress(batch){ var root=rootEl();if(!root||!batch)return;var counts=batchCounts(batch),modal=root.querySelector('.admin-confirm-modal');if(!modal){modal=document.createElement('div');modal.className='admin-confirm-modal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');root.appendChild(modal);}var current=batchEntries(batch).filter(function(entry){return entry.status==='processing';})[0];modal.innerHTML='<div class="admin-confirm-modal__panel" aria-live="polite"><h2>일괄 지급 처리 중</h2><p>완료 '+esc(counts.success+counts.replay+counts.failed+counts.uncertain)+' / '+esc(counts.total)+'</p><p>현재 처리: '+esc(current?((current.user&&current.user.nickname)||current.uid):'처리 준비 중')+'</p><p>성공 '+esc(counts.success)+' · 이미 처리됨 '+esc(counts.replay)+' · 실패 '+esc(counts.failed)+' · 확인 필요 '+esc(counts.uncertain)+'</p></div>'; }
  function synchronizeBatchUserResults(batch){ var entries=batchEntries(batch);entries.forEach(function(entry){if((entry.status!=='success'&&entry.status!=='replay')||typeof entry.after!=='number')return;var apply=function(user){if(!user||user.uid!==entry.uid)return;if(!user.currency)user.currency=userCurrency(user);user.currency[batch.resourceType]=entry.after;};(state.users||[]).forEach(apply);apply(state.searchResult);});renderDirectory();renderBatchTarget(); }
  function renderBatchResult(batch){ var root=rootEl(),counts=batchCounts(batch);if(!root)return;var modal=root.querySelector('.admin-confirm-modal');if(!modal){modal=document.createElement('div');modal.className='admin-confirm-modal';root.appendChild(modal);}var retry=batchService().retryable(batch);modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.innerHTML='<div class="admin-confirm-modal__panel"><h2>일괄 지급 결과</h2><p>전체 '+esc(counts.total)+'명 · 지급 완료 '+esc(counts.success)+'명 · 이미 처리됨 '+esc(counts.replay)+'명 · 실패 '+esc(counts.failed)+'명 · 결과 확인 필요 '+esc(counts.uncertain)+'명</p><ul class="admin-batch-result-list">'+batchEntries(batch).map(function(entry){return '<li><strong>'+esc((entry.user&&entry.user.nickname)||'게임 닉네임 없음')+'</strong> · '+esc((entry.user&&entry.user.loginId)||'로그인 ID 없음')+' · '+esc(batchResultMessage(entry))+'</li>';}).join('')+'</ul><div>'+(retry.length?'<button class="btn btn-success" type="button" data-admin-retry-uncertain>확인 필요 사용자 다시 시도</button>':'')+'<button class="btn" type="button" data-admin-result-close>결과 확인</button></div></div>';var close=modal.querySelector('[data-admin-result-close]');if(close)close.addEventListener('click',finalizeBatchResult);var retryButton=modal.querySelector('[data-admin-retry-uncertain]');if(retryButton)retryButton.addEventListener('click',retryUncertainEntries); }
  function runActiveBatch(isRetry){ var batch=state.activeBatch;if(!batch||isBatchProcessing())return;state.processing=true;state.batchUiState=isRetry?'retrying':'processing';setBatchControls(true);renderBatchProgress(batch);Promise.resolve(batchService().run(batch,firestore().grantAdminResource,state.context,function(updated){renderBatchProgress(updated);})).then(function(result){state.activeBatch=result;state.processing=false;state.batchUiState='result';setBatchControls(false);synchronizeBatchUserResults(result);renderBatchResult(result);loadHistory();}).catch(function(error){state.processing=false;state.batchUiState='result';setBatchControls(false);batchEntries(batch).forEach(function(entry){if(entry.status==='processing'||entry.status==='pending')entry.status='uncertain';});synchronizeBatchUserResults(batch);setStatus('grant',messageFor(error,'grant'),'error');renderBatchResult(batch);loadHistory();}); }
  function startConfirmedBatchGrant(){ if(!state.activeBatch||state.batchUiState!=='confirm')return;runActiveBatch(false); }
  function retryUncertainEntries(){ if(!state.activeBatch||!batchService().retryable(state.activeBatch).length)return;runActiveBatch(true); }
  function finalizeBatchResult(){ var batch=state.activeBatch;if(!batch)return;batchEntries(batch).forEach(function(entry){if(entry.status==='success'||entry.status==='replay')delete state.selectedUids[entry.uid];});var unresolved=batchEntries(batch).some(function(entry){return entry.status==='failed'||entry.status==='uncertain';});if(!unresolved){var form=rootEl()&&rootEl().querySelector('[data-admin-grant]');if(form)form.reset();state.activeBatch=null;state.batchUiState=null;}closeBatchModal();renderDirectory();renderBatchTarget(); }
  function handleSelectionChange(event){ if(isBatchProcessing())return;var check=event.target.closest('[data-user-check]'),all=event.target.closest('[data-select-visible]');if(check){setSelected(check.dataset.userCheck,check.checked);return;}if(all){(state.searchActive?state.serverSearchResults:visibleUsers()).forEach(function(user){setSelected(user.uid,all.checked,true);});renderDirectory();} }
  function backToLobby(){ if(isBatchProcessing())return;clear();if(state.context&&state.context.showLobby)state.context.showLobby(); }
  return {open:open,renderMenu:renderMenu,handleAuthStateChanged:handleAuthStateChanged,clear:clear,messageFor:messageFor,createActionId:createActionId,formatKst:formatKst,renderAdminUserCard:renderUserCard,renderAdminUserTable:userTable,buildSelectedUserSnapshot:selectedUserSnapshot,_state:state};
});
