(function(global){
  'use strict';
  var v2=global.GugudanV2;if(!v2)return;
  var palettes=[['#83dcff','#fff4a8'],['#202a44','#89a7ff'],['#ff9a3c','#ffe266'],['#77cfa8','#d9fff1'],['#f5a08d','#8bd7ff'],['#c58a62','#ffe0a8'],['#29445f','#b7d9f2'],['#b9815d','#f5d3a5'],['#f5e6b0','#bc9cff'],['#c9c9d8','#91a1cc'],['#d5f1ff','#fff'],['#86d2e8','#b9fff5'],['#65e7d5','#c997ff'],['#dbe8f4','#8db6e8'],['#65bfff','#f7fbff'],['#5be7c4','#b2fff0'],['#b98cff','#eef0ff'],['#69d7ff','#dbfff8'],['#ffd447','#ff8b45'],['#ff667d','#b169ff']];
  (v2.baseCats||[]).forEach(function(cat,index){cat.effectPalette=cat.effectPalette||{primary:palettes[index][0],secondary:palettes[index][1],glow:palettes[index][0]+'dd'};});
  var lastCompletion=null,lastStageId=null,complete=v2.adventureService&&v2.adventureService.completeStage;
  if(complete)v2.adventureService.completeStage=function(id,result){lastStageId=id;lastCompletion=complete(id,result);setTimeout(renderResultButtons,0);return lastCompletion;};
  function nextStage(id){var worlds=(v2.worlds||[]).filter(function(w){return w.enabled;}).sort(function(a,b){return a.order-b.order;}),stage=v2.adventureService.getStage(id);if(!stage)return null;var worldIndex=worlds.findIndex(function(w){return w.id===stage.worldId;});if(worldIndex<0)return null;var stageIndex=worlds[worldIndex].stageIds.indexOf(id);return stageIndex<worlds[worldIndex].stageIds.length-1?v2.adventureService.getStage(worlds[worldIndex].stageIds[stageIndex+1]):worlds[worldIndex+1]?v2.adventureService.getStage(worlds[worldIndex+1].stageIds[0]):null;}
  function renderResultButtons(){var actions=document.getElementById('adventure-result-actions');if(!actions||!lastCompletion||!lastCompletion.cleared)return;var next=nextStage(lastStageId);actions.innerHTML='<button id="phase56-next" class="game-button primary">'+(next?'다음 스테이지로':'월드맵으로')+'</button><button class="game-button secondary" onclick="openStageReady(\''+lastStageId+'\')">다시 도전</button><button class="game-button secondary" onclick="backToStageSelect()">스테이지 목록</button>';document.getElementById('phase56-next').onclick=function(){if(next)global.openStageReady(next.id);else global.openAdventureMap();};}
  function fragmentState(){var save=v2.storageService.loadSaveData(),data=save.collection.catFragments||{},result={normal:0,rare:0,hero:0,legendary:0},cats=[].concat(v2.baseCats||[],v2.seasonCats||[]);Object.keys(data).forEach(function(key){var cat=cats.find(function(item){return item.id===key;});if(cat)result[cat.rarity]+=Number(data[key])||0;else if(result[key]!==undefined)result[key]+=Number(data[key])||0;});return result;}
  function enhance(){
    var filters=document.getElementById('collection-filters'),summary=document.getElementById('collection-fragment-summary'),fragments=fragmentState();
    if(filters&&!summary){summary=document.createElement('p');summary.id='collection-fragment-summary';summary.className='collection-fragment-summary';filters.after(summary);}
    if(summary){var summaryText='고양이 조각 · 일반 '+fragments.normal+' · 희귀 '+fragments.rare+' · 영웅 '+fragments.hero+' · 전설 '+fragments.legendary;if(summary.textContent!==summaryText)summary.textContent=summaryText;}
    document.querySelectorAll('.cat-thumbnail-item').forEach(function(card){if(card.classList.contains('collection-cat-row'))return;var name=card.querySelector('strong'),badge=card.querySelector('small');if(!name)return;var cat=[].concat(v2.baseCats||[],v2.seasonCats||[]).find(function(item){return item.displayName===name.textContent;});if(!cat)return;if(badge){badge.classList.add('cat-thumbnail-rarity');if(badge.nextElementSibling!==name)card.insertBefore(badge,name);}var stars=card.querySelector('.duplicate-stars');if(stars&&!stars.classList.contains('collection-stars'))stars.classList.add('collection-stars');});
    document.querySelectorAll('.gacha-reveal-card .duplicate-stars:not(.gacha-stars)').forEach(function(stars){stars.classList.add('gacha-stars');});
  }
  if(v2.catPresentationRuntime){var oldFeedback=v2.catPresentationRuntime.playFeedback;v2.catPresentationRuntime.playFeedback=function(kind){var value=oldFeedback&&oldFeedback(kind);if(kind==='wrong'&&v2.effectService)v2.effectService.playWrong();return value;};}
  var debug=global.NyankoDebug=global.NyankoDebug||{};
  Object.assign(debug,{printNextAdventureStage:function(id){var next=nextStage(id);return next&&next.id;},testNextStageButton:function(id){lastStageId=id;lastCompletion={cleared:true};renderResultButtons();return nextStage(id);},printCatFragmentState:fragmentState,printCatFragmentStateByCat:function(id){return(v2.storageService.loadSaveData().collection.catFragments||{})[id]||0;},previewClosedGachaHouse:function(){var modal=document.getElementById('gacha-animation-modal');if(modal){modal.hidden=false;modal.className='gacha-modal';}},previewGachaDoorOpening:function(){var modal=document.getElementById('gacha-animation-modal');if(modal){modal.hidden=false;modal.className='gacha-modal animating';}},previewFullGachaSequence:function(rarity){if(debug.previewGachaAnimation)debug.previewGachaAnimation(rarity);}});
  var scheduled=false;new MutationObserver(function(){if(scheduled)return;scheduled=true;global.requestAnimationFrame(function(){scheduled=false;enhance();});}).observe(document.body,{childList:true,subtree:true});enhance();
})(window);
