(function (global) {
  'use strict';
  var v2 = global.GugudanV2, busy = false, names = { normal: '일반', rare: '희귀', hero: '영웅', legendary: '전설' };
  function id(value) { return document.getElementById(value); }
  function rates(config) { return Object.keys(config.rarityRates).map(function (key) { return names[key] + ' ' + Math.round(config.rarityRates[key] * 100) + '%'; }).join(' · '); }
  function currencyText(save) { return '🪙 ' + save.currency.coins + '코인 · 🎫 일반 ' + save.currency.normalTickets + '장 · 🌟 고급 ' + save.currency.premiumTickets + '장'; }
  function resultBox(result) { var box = id('pack-result'), cat = result.cat; box.hidden = false; box.className = 'pack-result rarity-' + result.rarity + ' revealing'; box.innerHTML = '<span class="rarity-badge">' + names[result.rarity] + '</span><img src="' + cat.image + '" alt="' + cat.displayName + '"><h3>' + (result.duplicate ? '중복 획득' : '새 고양이 획득!') + '</h3><strong>' + cat.displayName + '</strong><p>' + (result.duplicate ? names[result.rarity] + ' 조각 +' + result.fragments : '도감에 추가했어요.') + '</p>'; if (v2.assetLoader) v2.assetLoader.applyImageFallback(box.querySelector('img'), cat.fallbackImage, cat.id); setTimeout(function () { box.classList.remove('revealing'); busy = false; render(); }, 900); box.focus(); }
  function executeDraw(type, guestDraw) { var authenticated = Boolean(global.firebaseClient && global.firebaseClient.auth && global.firebaseClient.auth.currentUser); if (global.performDrawCatTransaction) return global.performDrawCatTransaction(type); if (authenticated) return Promise.reject(new Error('authenticated_gacha_handler_missing')); return Promise.resolve(guestDraw()); }
  function drawCoin() { if (busy) return; busy = true; executeDraw('coin', function () { return v2.coinDrawService.draw(); }).then(handleResult).catch(handleError); }
  function drawTicket(packId) { if (busy) return; busy = true; var drawType = packId === 'normalPack' ? 'normalTicket' : 'premiumTicket'; executeDraw(drawType, function () { return v2.cardPackService.openPack(packId); }).then(handleResult).catch(handleError); }
  function handleResult(result) { if (!result.ok) { busy = false; id('pack-message').textContent = '뽑기권이 부족하거나 뽑기를 완료하지 못했어요.'; return; } if (global.refreshCurrentUserData && global.showLobby) global.refreshCurrentUserData().then(function () { global.showLobby(); resultBox(result); }).catch(function () { resultBox(result); }); else resultBox(result); }
  function handleError(error) { busy = false; console.error('[GACHA SAVE ERROR]', error); id('pack-message').textContent = error && error.message === 'insufficient_ticket' ? '뽑기권이 부족하다냥!' : '뽑기 실행 중 오류가 발생했어요.'; }
  function premiumPreview(pickup) { if (!pickup.active) return ''; var cats = (v2.seasonCats || []).filter(function (cat) { return cat.seasonId === pickup.season.id; }); return '<article class="pack-card premiumPack ticket-pack summer-pickup"><h3>🌞 2026 여름 시즌 뽑기</h3><p>' + pickup.subtitle + '</p><p>같은 등급에서 등장 확률 2배!</p><p>등급별 확률은 기존 고급 뽑기와 동일합니다.</p><p>' + rates(v2.cardPackConfig.premiumPack) + '</p><div class="summer-pickup-preview">' + cats.map(function (cat) { return '<div><img src="' + cat.image + '" alt="' + cat.displayName + '"><span class="rarity-badge rarity-' + cat.rarity + '">' + names[cat.rarity] + '</span><small>' + cat.displayName + '</small></div>'; }).join('') + '</div><button class="game-button primary" ' + (v2.storageService.loadSaveData().currency.premiumTickets < 1 ? 'disabled' : '') + '>고급 뽑기권 1장으로 뽑기</button></article>'; }
  function render() { var save = v2.storageService.loadSaveData(), coin = v2.catDrawConfig, normal = v2.cardPackConfig.normalPack, pickup = v2.cardPackService.getPremiumPickup(), list = id('pack-list'); id('pack-currency').textContent = currencyText(save); list.innerHTML = '<article class="pack-card coin-draw"><h3>코인 뽑기</h3><p>' + rates({ rarityRates: coin.rarityRates }) + '</p><p>필요: ' + coin.cost + '코인</p><button class="game-button primary" ' + (save.currency.coins < coin.cost ? 'disabled' : '') + '>코인으로 뽑기</button></article><article class="pack-card ticket-pack"><h3>🎫 일반 티켓 뽑기</h3><p>표준 뽑기 확률을 사용합니다.</p><p>' + rates(normal) + '</p><button class="game-button primary" ' + (save.currency.normalTickets < 1 ? 'disabled' : '') + '>일반 뽑기권 1장 사용</button></article>' + premiumPreview(pickup) + '<article class="pack-card effect-preview-card"><h3>✨ 정답 이펙트 미리보기</h3><button class="game-button secondary">이펙트 보기</button></article>'; var buttons = list.querySelectorAll('button'); buttons[0].onclick = drawCoin; buttons[1].onclick = function () { drawTicket('normalPack'); }; var premiumButton = list.querySelector('.summer-pickup button'); if (premiumButton) premiumButton.onclick = function () { drawTicket('premiumPack'); }; buttons[buttons.length - 1].onclick = function () { if (v2.effectService) v2.effectService.playCorrect(10); }; if (v2.assetLoader) list.querySelectorAll('.summer-pickup-preview img').forEach(function (image) { v2.assetLoader.applyImageFallback(image, 'assets/placeholders/cat-placeholder.svg'); }); }
  function open() { busy = false; id('pack-result').hidden = true; id('pack-message').textContent = ''; render(); showScreen('card-pack-screen'); setTimeout(function () { id('card-pack-title').focus(); }, 0); }
  global.openCardPackScreen = open;
})(window);
