(function(global){'use strict';
var v2=global.GugudanV2,run=null,RECENT=[];
function id(x){return document.getElementById(x);}function eligibility(){var p=global.getDivisionProgress?global.getDivisionProgress():{storyCompleted:false,divisionExactCompletions:0},exact=Math.max(0,Number(p.divisionExactCompletions)||0);return{exact:Boolean(p.storyCompleted),remainder:Boolean(p.storyCompleted)&&exact>=10,count:exact};}
function notice(mode){var e=eligibility();alert(mode==='divisionExact'?'스토리 모드를 모두 완료하면 나눗셈 모드가 열린다냥!':'나눗셈을 10판 완료하면 열린다냥!\n현재 완료: '+e.count+' / 10');}
function renderCards(){[['divisionExact','division-exact-card'],['divisionRemainder','division-remainder-card']].forEach(function(x){var card=id(x[1]);if(!card)return;var e=eligibility(),open=x[0]==='divisionExact'?e.exact:e.remainder,status=card.querySelector('.division-mode-status');card.classList.toggle('mode-card--locked',!open);card.setAttribute('aria-disabled',String(!open));status.textContent=open?'플레이 가능':x[0]==='divisionExact'?'스토리 모드를 모두 완료하면 열립니다.':'나눗셈 완료 '+e.count+' / 10';card.onclick=function(){if(!open)return notice(x[0]);start(x[0]);};});}
function options(answer,min,max){var a=[answer],n=answer-1;while(a.length<4){if(n>=min&&n<=max&&a.indexOf(n)<0)a.push(n);n++;if(n>max)n=min;}return a.sort(function(){return Math.random()-.5;});}
function question(mode){var divisor=2+Math.floor(Math.random()*8),quotient=1+Math.floor(Math.random()*9),remainder=mode==='divisionRemainder'?1+Math.floor(Math.random()*(divisor-1)):0,dividend=divisor*quotient+remainder,key=dividend+'/'+divisor;if(RECENT[0]===key)return question(mode);RECENT=[key];return{divisor:divisor,quotient:quotient,remainder:remainder,dividend:dividend,text:dividend+' ÷ '+divisor+' = ?',step:'quotient'};}
function feedback(ok,text){if(global.setGameAnswerFeedback)global.setGameAnswerFeedback(ok?'correct':'wrong',text);else{id('feedback').className='game-answer-feedback is-'+(ok?'correct':'wrong');id('feedback').textContent=text;}}
function render(){var s=global.gameSession;if(!s||!run)return;if(s.answeredCount>=20){global.finalizeGameSession({reason:'question_limit',success:true});return;}run.current=question(s.mode);s.currentQuestion=run.current;id('q-counter').textContent='문제: '+(s.answeredCount+1)+'/20';id('progress-bar').style.width=(s.answeredCount/20*100)+'%';id('live-points').textContent='현재 획득: '+(s.correctCount*10)+'P';id('question').textContent=run.current.text+(s.mode==='divisionRemainder'?'\n몫을 골라주세요':'');id('feedback').className='';id('feedback').textContent='';answers(run.current.quotient,'quotient');}
function answers(answer,step){var q=run.current,box=id('options-container');box.innerHTML='';var list=options(answer,step==='remainder'?0:1,step==='remainder'?q.divisor-1:12);list.forEach(function(x){var b=document.createElement('button');b.type='button';b.className='btn btn-answer game-answer-button';b.textContent=x;b.onclick=function(){choose(x,step);};box.appendChild(b);});}
function choose(value,step){var s=global.gameSession,q=run.current;if(!s||run.locked)return;if(step==='quotient'&&value===q.quotient&&s.mode==='divisionRemainder'){id('question').textContent=q.text+'\n선택한 몫: '+value+'\n나머지를 골라주세요';feedback(true,'정답이다냥!');answers(q.remainder,'remainder');return;}run.locked=true;var ok=step==='quotient'?value===q.quotient:value===q.remainder;s.answeredCount++;if(ok)s.correctCount++;else s.wrongCount++;s.results.push({left:q.dividend,right:q.divisor,submittedAnswer:value,correctAnswer:step==='quotient'?q.quotient:q.remainder,isCorrect:ok,elapsedMs:0});document.querySelectorAll('#options-container button').forEach(function(b){b.disabled=true;});feedback(ok,ok?'정답이다냥!':'아쉽다냥! 정답은 몫 '+q.quotient+', 나머지 '+q.remainder+'다냥!');setTimeout(function(){run.locked=false;render();},650);}
function start(mode){var e=eligibility();if((mode==='divisionExact'&&!e.exact)||(mode==='divisionRemainder'&&!e.remainder)){notice(mode);return false;}if(global.clearClassicRuntime)global.clearClassicRuntime();if(global.clearPhase2Runtime)global.clearPhase2Runtime();var s=global.createNewGameSession({mode:mode,worldId:null,stageNumber:null,stageType:null,stageId:null});s.status='playing';s.questionCount=20;s.results=[];run={locked:false,current:null};if(global.renderGameShell)global.renderGameShell({mode:mode,title:mode==='divisionExact'?'나눗셈':'몫과 나머지',stageLabel:'20문제 도전',showTimer:false,showCombo:false,showBossHp:false,enemyType:'cat'});global.showScreen('play-screen');render();return true;}
global.startDivisionMode=start;global.renderDivisionModeCards=renderCards;
global.NyankoDebug=global.NyankoDebug||{};global.NyankoDebug.divisionModes={eligibility:eligibility,createQuestion:question};
})(window);
