(function (global) {
  'use strict';
  var v2 = global.GugudanV2, stateApi = v2.gameState, state = stateApi.state, config = v2.gameConfig;
  var modeTimer = null, modeEndAt = null, transitionTimer = null, activeMode = null, lastMode = 'timeAttack';
  var rankingMode = 'classic', rankingPeriod = 'allTime';
  var GAME_MODES = { CLASSIC: 'classic', TIME_ATTACK: 'timeAttack', ENDLESS: 'endless', ADVENTURE: 'adventure' };
  function byId(id) { return document.getElementById(id); }
  function clearTimers() { if (modeTimer) clearInterval(modeTimer); if (transitionTimer) clearTimeout(transitionTimer); modeTimer = null; transitionTimer = null; modeEndAt = null; }
  function playerContext() { return global.getCurrentPlayerContext ? global.getCurrentPlayerContext() : { nickname: 'GUEST', isGuest: true }; }
  function setVisible(selector, visible) { document.querySelectorAll(selector).forEach(function (element) { element.style.display = visible ? '' : 'none'; }); }
  function prepareResultLayout(isPhase2) { setVisible('.legacy-result', !isPhase2); byId('total-stats').style.display = isPhase2 ? 'none' : byId('total-stats').style.display; byId('reward-box').style.display = 'none'; byId('phase2-result-panel').style.display = isPhase2 ? 'block' : 'none'; byId('phase2-result-actions').style.display = isPhase2 ? 'block' : 'none'; byId('legacy-result-actions').style.display = isPhase2 ? 'none' : 'block'; byId('ranking-controls').style.display = isPhase2 ? 'block' : 'none'; }
  function prepareClassicUI() { clearTimers(); activeMode = null; byId('mode-status').className = 'mode-status'; byId('mode-status').innerHTML = ''; byId('phase2-exit-button').style.display = 'none'; byId('timer-bar').parentElement.style.display = ''; byId('progress-bar').parentElement.style.display = ''; prepareResultLayout(false); document.querySelector('#result-screen > h1').textContent = '🎉 모험 끝냥! 🎉'; }
  function clearPhase2Runtime() { clearTimers(); if (activeMode && state.status === 'playing') stateApi.finishGame('manual_exit'); activeMode = null; byId('phase2-exit-button').style.display = 'none'; document.body.classList.remove('time-warning-mode','time-attack-critical'); }
  function startPhase2Mode(mode, overrides) {
    if (mode !== GAME_MODES.TIME_ATTACK && mode !== GAME_MODES.ENDLESS) return;
    if (!config.modes[mode] || !config.modes[mode].enabled) return;
    clearTimers(); prepareResultLayout(true); activeMode = mode; lastMode = mode; var rules = config.modes[mode], options = {};
    if (mode === GAME_MODES.TIME_ATTACK) options.durationSeconds = overrides && overrides.durationSeconds || rules.defaultSeconds;
    if (mode === GAME_MODES.ENDLESS) options.lives = rules.defaultLives;
    stateApi.startGame(mode, options); state.selectedCatId = v2.storageService.loadSaveData().profile.selectedCatId;
    var context = playerContext(), save = v2.storageService.loadSaveData(); if (!context.isGuest && context.nickname) save.profile.nickname = context.nickname; v2.storageService.saveSaveData(save);
    byId('phase2-exit-button').style.display = 'inline-block'; byId('mode-status').className = 'mode-status active'; byId('feedback').textContent = '';
    byId('timer-bar').parentElement.style.display = mode === GAME_MODES.TIME_ATTACK ? '' : 'none'; byId('progress-bar').parentElement.style.display = mode === GAME_MODES.TIME_ATTACK ? '' : 'none';
    showScreen('play-screen'); renderModeStatus(); nextModeQuestion();
    if (mode === GAME_MODES.TIME_ATTACK) startModeTimer(options.durationSeconds);
  }
  function startModeTimer(seconds) { clearInterval(modeTimer); modeEndAt = Date.now() + seconds * 1000; updateModeTimer(); modeTimer = setInterval(updateModeTimer, 100); }
  function updateModeTimer() {
    if (activeMode !== GAME_MODES.TIME_ATTACK || state.status !== 'playing' || !modeEndAt) return;
    var remainingMs = Math.max(0, modeEndAt - Date.now()), remaining = Math.ceil(remainingMs / 1000); state.remainingSeconds = remaining;
    var percent = Math.max(0, remainingMs / (state.durationSeconds * 1000) * 100); byId('timer-bar').style.width = percent + '%';
    var warning = remaining <= config.modes.timeAttack.warningSeconds; byId('mode-status').classList.toggle('time-warning', warning);byId('mode-status').classList.toggle('time-critical',remaining<=5);document.body.classList.toggle('time-attack-critical',remaining<=5); byId('timer-bar').style.backgroundColor = warning ? '#F44336' : '#FFB347'; renderModeStatus();
    if (remainingMs <= 0) finishModeGame('time_up');
  }
  function difficultyRules() { var level = state.difficultyLevel; if (activeMode === GAME_MODES.TIME_ATTACK) return { min: 2, max: 9, options: 4, reverse: .25, memory: 5, trap: state.correctCount >= 20 }; if (level === 1) return { min: 2, max: 5, options: 4, reverse: .1, memory: 5, trap: false }; if (level === 2) return { min: 2, max: 9, options: 4, reverse: .35, memory: 7, trap: false }; return { min: 2, max: 9, options: 6, reverse: .5, memory: 10, trap: true }; }
  function createQuestion() { var rules = difficultyRules(), attempts = 0, a, b, key; do { a = Math.floor(Math.random() * (rules.max - rules.min + 1)) + rules.min; b = Math.floor(Math.random() * 9) + 1; key = a + 'x' + b; attempts += 1; } while (state.recentQuestions.indexOf(key) >= 0 && attempts < 30); state.recentQuestions.push(key); state.recentQuestions = state.recentQuestions.slice(-rules.memory); var reverse = Math.random() < rules.reverse, left = reverse ? b : a, right = reverse ? a : b; return { left: left, right: right, answer: a * b, key: key, optionsCount: rules.options, trap: rules.trap }; }
  function nextModeQuestion() { if (state.status !== 'playing') return; try { state.inputLocked = false; if (v2.effectService && typeof v2.effectService.clear === 'function') { v2.effectService.clear(); } var question = createQuestion(); state.currentQuestion = question; byId('question').textContent = question.left + ' X ' + question.right + ' = ?'; byId('question').className = 'question-text'; byId('feedback').textContent = ''; renderAnswers(question); renderModeStatus(); } catch (error) { console.error('[mode] 문제 생성 실패', error); finishModeGame('error'); } }
  function renderAnswers(question) { var options = v2.questionGenerator.createOptions(question.answer, question.optionsCount, question.trap), container = byId('options-container'); container.innerHTML = ''; options.forEach(function (option) { var button = document.createElement('button'); button.className = 'btn btn-answer'; if (question.optionsCount > 4) button.classList.add('btn-answer-small'); button.textContent = option; button.type = 'button'; button.onclick = function () { submitModeAnswer(option, button); }; container.appendChild(button); }); }
  function markAnswerButtons(selectedButton, correctAnswer, correct) { document.querySelectorAll('#options-container .btn-answer').forEach(function (button) { button.disabled = true; if (Number(button.textContent) === Number(correctAnswer)) button.classList.add('answer-choice-correct'); }); if (selectedButton && !correct) selectedButton.classList.add('answer-choice-wrong'); }
  function submitModeAnswer(answer, selectedButton) { if (state.status !== 'playing' || state.inputLocked) return; if (activeMode === GAME_MODES.TIME_ATTACK && modeEndAt && Date.now() >= modeEndAt) { finishModeGame('time_up'); return; } state.inputLocked = true; var correct = answer === state.currentQuestion.answer; markAnswerButtons(selectedButton, state.currentQuestion.answer, correct); if (correct) handleModeCorrect(); else handleModeWrong(); }
  function playModeSound(correct) { try { if(v2.soundService){if (correct) v2.soundService.playCorrectSound(); else v2.soundService.playWrongSound();}else playSound(correct ? 'correct' : 'wrong'); if(v2.catPresentationRuntime)v2.catPresentationRuntime.playFeedback(correct?'correct':'wrong'); } catch (error) { playSound(correct ? 'correct' : 'wrong'); } }
  function handleModeCorrect() { var nextCombo = state.combo + 1, rules = config.modes[activeMode], points = v2.scoreManager.calculateModeAnswerScore(nextCombo, rules); stateApi.recordCorrectAnswer(points); playModeSound(true); var praise = ''; try { praise = v2.effectService.playCorrect(nextCombo); } catch (error) { console.error('[Mode correct effect error]', error); } byId('feedback').textContent = activeMode === GAME_MODES.TIME_ATTACK ? '' : praise + ' +' + points + 'P'; byId('feedback').className = activeMode === GAME_MODES.TIME_ATTACK ? '' : 'correct-anim'; byId('question').className = 'question-text correct-anim'; if (activeMode === GAME_MODES.ENDLESS && state.correctCount % rules.difficultyIncreaseInterval === 0) { stateApi.increaseDifficulty(); byId('feedback').textContent = '난이도 상승! Lv.' + state.difficultyLevel; } continueAfterAnswer(activeMode === GAME_MODES.TIME_ATTACK ? 360 : 450); }
  function handleModeWrong() { stateApi.recordWrongAnswer(); playModeSound(false); byId('feedback').textContent = activeMode === GAME_MODES.TIME_ATTACK ? '' : '💦 오답! 정답은 ' + state.currentQuestion.answer; byId('feedback').className = activeMode === GAME_MODES.TIME_ATTACK ? '' : 'wrong-anim'; byId('question').className = 'question-text wrong-anim'; if (activeMode === GAME_MODES.ENDLESS) { state.lives = Math.max(0, state.lives - 1); renderModeStatus(); if (state.lives === 0) { transitionTimer = setTimeout(function () { finishModeGame('no_lives'); }, 550); return; } } continueAfterAnswer(activeMode === GAME_MODES.TIME_ATTACK ? 420 : 550); }
  function continueAfterAnswer(delay) { renderModeStatus(); transitionTimer = setTimeout(function () { if (state.status === 'playing') nextModeQuestion(); }, delay); }
  function renderModeStatus() { if (!activeMode) return; var accuracy = state.totalQuestions ? Math.round(state.correctCount / state.totalQuestions * 100) : 0; byId('q-counter').textContent = activeMode === GAME_MODES.TIME_ATTACK ? '푼 문제: ' + state.totalQuestions : '맞힌 문제: ' + state.correctCount; byId('current-accuracy').textContent = '정확도: ' + accuracy + '%'; byId('live-points').textContent = '현재 획득: ' + state.score + 'P'; if (activeMode === GAME_MODES.TIME_ATTACK) byId('mode-status').innerHTML = '<span>⏱️ 남은 시간 <strong>' + state.remainingSeconds + '초</strong></span><span>콤보 ' + state.combo + '</span><span>최고 ' + state.bestCombo + '</span>'; else byId('mode-status').innerHTML = '<span>🐾 남은 목숨 <strong>' + state.lives + '</strong></span><span>콤보 ' + state.combo + '</span><span>최고 ' + state.bestCombo + '</span><span>난이도 Lv.' + state.difficultyLevel + '</span>'; }
  function buildResult(reason) { var total = state.totalQuestions, accuracy = total ? Math.round(state.correctCount / total * 100) : 0; return { sessionId: state.sessionId, mode: activeMode, score: state.score, correctCount: state.correctCount, wrongCount: state.wrongCount, totalQuestions: total, accuracy: accuracy, bestCombo: state.bestCombo, difficultyLevel: state.difficultyLevel, durationSeconds: state.durationSeconds, livesStarted: state.initialLives, highestDifficultyLevel: state.difficultyLevel, finishReason: reason, startedAt: state.startedAt, finishedAt: state.finishedAt, playedAt: new Date().toISOString() }; }
  function finishModeGame(reason) { if (state.status === 'finished') return; if (!stateApi.finishGame(reason)) return; clearTimers(); document.body.classList.remove('time-attack-critical'); disableBtns(); var result = buildResult(reason), shouldRecord = reason !== 'error', local = shouldRecord ? v2.storageService.recordGame(result) : { isPersonalBest: false }, coinReward = shouldRecord && result.mode === GAME_MODES.TIME_ATTACK ? v2.modeRewardService.claim('timeAttack', result, { isPersonalBest: local.isPersonalBest }) : null; if (v2.seasonService && shouldRecord && v2.isFeatureEnabled('seasonMissions')) v2.seasonService.recordGameResult(result); if (v2.dailyMissionService && shouldRecord) v2.dailyMissionService.recordGameResult(result); showModeResult(result, local.isPersonalBest, coinReward); if (reason === 'time_up' || reason === 'no_lives') submitModeRanking(result); }
  function showModeResult(result, isBest, coinReward) { prepareResultLayout(true); var title = result.mode === GAME_MODES.TIME_ATTACK ? '⏱️ 타임어택 종료' : '🐾 무제한 도전 종료', rewardHtml = coinReward && coinReward.ok ? '<div class="mode-coin-reward"><strong>획득 코인 +' + coinReward.parts.total + '코인</strong><small>완료 ' + coinReward.parts.completion + ' · 정답 ' + coinReward.parts.correct + (coinReward.parts.perfect ? ' · 완벽 ' + coinReward.parts.perfect : '') + (coinReward.parts.personalBest ? ' · 최고 기록 ' + coinReward.parts.personalBest : '') + '</small></div>' : ''; document.querySelector('#result-screen > h1').textContent = title; byId('phase2-result-title').textContent = result.finishReason === 'manual_exit' ? '도전을 종료했어요' : title; byId('phase2-result-stats').innerHTML = '<div class="phase2-result-grid"><span>최종 점수 <b>' + result.score + 'P</b></span><span>정답 <b>' + result.correctCount + '</b></span><span>오답 <b>' + result.wrongCount + '</b></span><span>정확도 <b>' + result.accuracy + '%</b></span><span>최고 콤보 <b>' + result.bestCombo + '</b></span>' + (result.mode === GAME_MODES.ENDLESS ? '<span>도달 난이도 <b>Lv.' + result.difficultyLevel + '</b></span>' : '') + '</div>' + rewardHtml; byId('phase2-best-badge').style.display = isBest ? 'block' : 'none'; byId('phase2-ranking-status').textContent = result.finishReason === 'manual_exit' ? '수동 종료 기록은 순위에 등록하지 않습니다.' : '로컬 기록 저장 완료 · 순위 등록 확인 중'; byId('ranking-box').style.display = 'none'; showScreen('result-screen'); byId('phase2-result-panel').focus(); }
  function submitModeRanking(result) { var context = playerContext(), save = v2.storageService.loadSaveData(); if (context.isGuest || !context.nickname || result.score <= 0 || result.totalQuestions <= 0) { byId('phase2-ranking-status').textContent = '로컬 기록 저장 완료 · 로그인 기록만 온라인 순위에 등록됩니다.'; return; } var payload = Object.assign({}, result, { nickname: context.nickname, playerId: save.profile.playerId, rankingId: save.profile.rankingId || '' }); Promise.all([v2.rankingService.submitScore(payload), v2.rankingService.submitOverall(payload)]).then(function (responses) { var ok = responses[0].ok && responses[1].ok; byId('phase2-ranking-status').textContent = ok ? '로컬 기록 및 주간·전체 순위 등록 완료' : '로컬 기록 저장 완료 · 온라인 순위 등록 실패'; }); }
  function exitPhase2ToMain() { if (!activeMode || state.status !== 'playing') return showLobby(); if (global.confirm && !global.confirm('진행 중인 도전을 끝내고 메인으로 돌아갈까요?')) return; finishModeGame('manual_exit'); showLobby(); }
  function restartPhase2Mode() { startPhase2Mode(lastMode); }
  function showModeSelection() { showLobby(); var first = document.querySelector('.mode-card:not([disabled])'); if (first) first.focus(); }
  function openRankings() { clearTimers(); prepareResultLayout(true); byId('phase2-result-panel').style.display = 'none'; byId('phase2-result-actions').style.display = 'none'; byId('legacy-result-actions').style.display = 'block'; byId('legacy-result-actions').querySelector('.btn-success').textContent = '메인으로'; byId('ranking-box').style.display = 'block'; byId('ranking-controls').style.display = 'block'; rankingMode = 'classic'; rankingPeriod = 'allTime'; document.querySelector('#result-screen > h1').textContent = '🏆 냥코 순위'; showScreen('result-screen'); loadModeRanking(); }
  function setRankingMode(mode) { rankingMode = mode; if (mode === 'classic') rankingPeriod = 'allTime'; loadModeRanking(); }
  function setRankingPeriod(period) { rankingPeriod = rankingMode === 'classic' ? 'allTime' : period; loadModeRanking(); }
  function updateRankingButtons() { document.querySelectorAll('[data-mode]').forEach(function (button) { button.classList.toggle('active', button.dataset.mode === rankingMode); }); document.querySelectorAll('[data-period]').forEach(function (button) { button.classList.toggle('active', button.dataset.period === rankingPeriod); button.disabled = rankingMode === 'classic' && button.dataset.period === 'monthly'; }); }
  function loadModeRanking() { updateRankingButtons(); var list = byId('ranking-list'), retry = byId('ranking-retry'); retry.style.display = 'none'; list.innerHTML = '<p style="text-align:center;">순위를 불러오는 중...</p>'; if (rankingMode === 'classic') { byId('ranking-period-label').textContent = '기존 기본 도전 전체 순위'; updateGlobalRanking(); return; } var method = rankingPeriod === 'monthly' ? 'getMonthlyRanking' : 'getAllTimeRanking'; v2.rankingService[method]({ mode: rankingMode, limit: 10 }).then(function (response) { if (response.range) byId('ranking-period-label').textContent = response.range.label + ' (한국 시간)'; else if(response.monthKey)byId('ranking-period-label').textContent=response.monthKey+' 월간 (한국 시간)'; else byId('ranking-period-label').textContent = '전체 기간'; if (!response.ok) { var code = response.error && response.error.code || ''; var guide = code.indexOf('permission') >= 0 ? 'Firebase에서 modeRankings 읽기 권한을 확인해 주세요.' : code.indexOf('index') >= 0 || code === 'failed-precondition' ? 'Firebase 복합 인덱스를 만들어 주세요.' : response.reason === 'firebase_unavailable' ? '인터넷 연결과 Firebase 초기화를 확인해 주세요.' : '잠시 후 다시 시도해 주세요.'; list.innerHTML = '<p style="text-align:center; color:#B00020;">순위를 불러오지 못했어요.<br><small>' + guide + '</small></p>'; retry.style.display = 'inline-block'; return; } renderModeRanking(response.records); }); }
  function renderModeRanking(records) { var list = byId('ranking-list'), context = playerContext(); list.innerHTML = ''; if (!records.length) { list.innerHTML = '<p style="text-align:center;">아직 등록된 기록이 없어요.<br>첫 번째 냥코 도전자가 되어보세요!</p>'; return; } records.forEach(function (record, index) { var item = document.createElement('div'); item.className = 'mode-ranking-item'; if (record.nickname === context.nickname) item.style.background = '#FFF0F5'; var date = record.playedAt ? new Date(record.playedAt).toLocaleDateString('ko-KR') : '-'; item.innerHTML = '<div class="mode-ranking-main"><b>' + (index + 1) + '위 ' + escapeHtml(record.nickname || '익명') + '</b><strong>' + record.score + 'P</strong></div><div class="mode-ranking-meta"><span>정답 ' + record.correctCount + ' · 최고 콤보 ' + record.bestCombo + (record.mode === 'endless' ? ' · Lv.' + record.difficultyLevel : '') + '</span><span>' + date + '</span></div>'; list.appendChild(item); }); }
  function escapeHtml(value) { var div = document.createElement('div'); div.textContent = String(value); return div.innerHTML; }
  function validateGameConfig() { var errors = []; if (!config.modes.timeAttack.enabled || config.modes.timeAttack.defaultSeconds <= 0) errors.push('타임어택 설정 오류'); if (config.modes.endless.enabled && config.modes.endless.defaultLives < 1) errors.push('무제한 설정 오류'); return { valid: !errors.length, errors: errors }; }
  function validateSaveData() { var data = v2.storageService.loadSaveData(); return { valid: data.schemaVersion === 3 && Array.isArray(data.gameHistory) && data.gameHistory.length <= 50, data: data }; }
  function validateRankingResult(result) { return v2.rankingService.validateScoreSubmission(result); }
  function simulate(mode, reason) { var snapshot = JSON.parse(JSON.stringify(state)); stateApi.startGame(mode, mode === 'timeAttack' ? { durationSeconds: 5 } : { lives: 3 }); stateApi.recordCorrectAnswer(10); stateApi.recordWrongAnswer(); if (mode === 'endless') state.lives = 0; stateApi.finishGame(reason); var simulated = JSON.parse(JSON.stringify(state)); Object.keys(state).forEach(function (key) { delete state[key]; }); Object.assign(state, snapshot); return simulated; }
  global.startPhase2Mode = startPhase2Mode; global.clearPhase2Runtime = clearPhase2Runtime; global.prepareClassicUI = prepareClassicUI; global.exitPhase2ToMain = exitPhase2ToMain; global.restartPhase2Mode = restartPhase2Mode; global.showModeSelection = showModeSelection; global.openRankings = openRankings; global.setRankingMode = setRankingMode; global.setRankingPeriod = setRankingPeriod; global.loadModeRanking = loadModeRanking;
  global.NyankoDebug = { validateGameConfig: validateGameConfig, validateSaveData: validateSaveData, validateRankingResult: validateRankingResult, getKoreanWeekRange: v2.rankingService.getKoreanWeekRange, simulateTimeAttackEnd: function () { return simulate('timeAttack','time_up'); }, simulateEndlessGameOver: function () { return simulate('endless','no_lives'); }, printCurrentGameState: function () { console.table(state); return JSON.parse(JSON.stringify(state)); } };
})(window);
