const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;
class El{constructor(id){this.id=id;this.style={};this.children=[];this.classList={add(){},remove(){}};this.disabled=false;this._html='';}set innerHTML(v){this._html=v;this.children=[];}get innerHTML(){return this._html;}appendChild(n){this.children.push(n);}focus(){}querySelector(){return this.children[0]||new El();}setAttribute(){}}
const ids=['world-list','adventure-total-stars','stage-grid','stage-select-title','stage-select-subtitle','ready-stage-number','stage-ready-title','stage-ready-card','live-points','q-counter','current-accuracy','progress-bar','boss-hp','boss-hp-text','boss-hp-bar','question','options-container','feedback','skill-hud','skill-cat-image','skill-status','manual-skill-button','phase2-exit-button','mode-status','boss-panel','boss-name','boss-image','timer-bar','adventure-result-number','adventure-result-title','adventure-result-cat','adventure-result-stars','adventure-result-stats','adventure-rewards','adventure-unlock-copy','adventure-result-actions','adventure-result-card'];const els={};ids.forEach(id=>els[id]=new El(id));
global.document={getElementById:id=>els[id]||(els[id]=new El(id)),createElement:()=>new El(),querySelectorAll:selector=>selector.includes('options-container')?els['options-container'].children:[]};global.showScreen=()=>{};global.clearPhase2Runtime=()=>{};global.clearClassicRuntime=()=>{};
const stages={};function make(id,type,count){const boss=type==='midBoss'||type==='boss';return{id,worldId:'world_01',displayNumber:id,type,chapter:1,stageNumber:Number(id.slice(-2)),rules:{tables:[2],questionCount:count,answerOptionCount:4,lives:3,timeLimitSeconds:null},boss:boss?{name:'test',maximumHp:count,image:''}:null};}['stage_01_01','stage_01_05','stage_01_10','stage_02_05','stage_02_10','stage_03_05','stage_03_10'].forEach(id=>stages[id]=make(id,id.endsWith('05')?'midBoss':id.endsWith('10')?'boss':'normal',id.endsWith('10')?12:id.endsWith('05')?8:5));
global.GugudanV2={baseCats:[{id:'base_normal_01',displayName:'테스트 냥이',image:'',fallbackImage:'',skill:null}],seasonCats:[],worlds:[],questionGenerator:{createOptions:a=>[a,a+1,a+2,a+3]},releasePolicyService:{getSelectedCat(){return this.cat||(this.cat=global.GugudanV2.baseCats[0]);}},assetLoader:{applyImageFallback(){}},effectService:{playCorrect(){return'정답';}},adventureService:{loadProgress(){return{totalStars:0,unlockedWorldIds:[],unlockedStageIds:[],clearedStageIds:[],stageRecords:{}};},getStage:id=>stages[id],getWorld(){},completeStage(){return{cleared:false,stars:0};},unlockStage(){},unlockWorld(){},resetForTesting(){},validateAdventureProgress(){return[];}},rewardService:{claimStageRewards(){return{ok:false,reward:{}};}},modeRewardService:{claim(){return{ok:false};}},dailyMissionService:{recordGameResult(){}},isFeatureEnabled(){return false;}};
vm.runInThisContext(fs.readFileSync('js/game/adventureEngine.js','utf8'),{filename:'adventureEngine.js'});
async function run(id){NyankoDebug.startAdventureStage(id);let s=NyankoDebug.printAdventureState();assert.equal(s.status,'questionActive');for(let i=0;i<3;i++){assert.equal(NyankoDebug.simulateAdventureAnswer(true),true);await new Promise(r=>setTimeout(r,760));s=NyankoDebug.printAdventureState();assert.equal(s.answeredCount,i+1);assert.equal(s.status,'questionActive');assert.equal(s.isInputLocked,false);if(stages[id].boss)assert.equal(s.bossHp,stages[id].boss.maximumHp-(i+1));}return s;}
(async()=>{const results={};for(const id of Object.keys(stages))results[id]=await run(id);console.log(JSON.stringify({passed:true,stages:results},null,2));})().catch(error=>{console.error(error);process.exitCode=1;});
