(function (global) {
  'use strict';
  function assert(condition,message){if(!condition)throw new Error(message);}
  function cat(id){return global.GugudanV2.baseCats.find(function(item){return item.id===id;});}
  function runPhase4Validation(){var v2=global.GugudanV2,storage=v2.storageService;storage.resetSaveData();var save=storage.loadSaveData();assert(save.schemaVersion===7,'스키마 5 기본값 실패');assert(save.collection.ownedCatIds[0]==='base_normal_01'&&save.profile.selectedCatId==='base_normal_01','초기 고양이 실패');assert(v2.validators.validateCurrencyData(save.currency).valid,'재화 검증 실패');assert(v2.validators.validateCollectionData(save.collection).valid,'수집 검증 실패');assert(v2.validators.validateRewardConfig().valid,'보상 설정 실패');assert(v2.validators.validateCardPackConfig().valid,'팩 확률 실패');assert(v2.validators.validateCatSkillData().valid,'스킬 데이터 실패');
    var stage=v2.stages[0],first=v2.rewardService.claimStageRewards({sessionId:'reward_first',stage:stage,cleared:true,stars:1});assert(first.ok&&first.reward.coins===120&&first.reward.normalTickets===1,'최초 보상 실패');var duplicate=v2.rewardService.claimStageRewards({sessionId:'reward_first',stage:stage,cleared:true,stars:1});assert(!duplicate.ok&&duplicate.reason==='already_claimed','세션 중복 지급 차단 실패');var repeat=v2.rewardService.claimStageRewards({sessionId:'reward_repeat',stage:stage,cleared:true,stars:1});assert(repeat.ok&&repeat.reward.coins===20&&!repeat.reward.normalTickets,'반복 보상 실패');var stars=v2.rewardService.claimStageRewards({sessionId:'reward_stars',stage:stage,cleared:true,stars:3});assert(stars.ok&&stars.reward.starCoins===80,'별 1→3 차액 보상 실패');
    save=storage.loadSaveData();save.currency.normalTickets=2;save.currency.premiumTickets=1;storage.saveSaveData(save);var pack=v2.cardPackService.openPack('normalPack',0,0.4);assert(pack.ok&&pack.rarity==='normal','일반 팩 개봉 실패');var before=storage.loadSaveData().currency.normalTickets;var duplicatePack=v2.cardPackService.openPack('normalPack',0,0);assert(duplicatePack.ok&&duplicatePack.duplicate&&duplicatePack.fragments===1,'중복 카드 처리 실패');assert(storage.loadSaveData().currency.normalTickets===before-1,'티켓 차감 실패');
    var skill=v2.skillEngine;skill.initializeSkillSession({sessionId:'lightning',mode:'timeAttack',selectedCat:cat('base_hero_01'),isRankedRun:true});var lightning=skill.handleSkillTrigger({trigger:'combo',mode:'timeAttack',gameState:{combo:10,isRankedRun:true},selectedCat:cat('base_hero_01')});var same=skill.handleSkillTrigger({trigger:'combo',mode:'timeAttack',gameState:{combo:10,isRankedRun:true},selectedCat:cat('base_hero_01')});assert(lightning.activated&&!same.activated,'번개 중복 방지 실패');skill.initializeSkillSession({sessionId:'ranked',mode:'timeAttack',selectedCat:cat('base_hero_04'),isRankedRun:true});assert(!skill.handleSkillTrigger({trigger:'timed_start',mode:'timeAttack',gameState:{isRankedRun:true},selectedCat:cat('base_hero_04')}).activated,'공식 타임어택 시간 스킬 차단 실패');skill.initializeSkillSession({sessionId:'shield',mode:'adventure',selectedCat:cat('base_hero_02')});var shield=skill.handleSkillTrigger({trigger:'wrong',mode:'adventure',gameState:{},selectedCat:cat('base_hero_02')});var shield2=skill.handleSkillTrigger({trigger:'wrong',mode:'adventure',gameState:{},selectedCat:cat('base_hero_02')});assert(shield.preventLifeLoss&&!shield2.activated,'실드 1회 제한 실패');skill.initializeSkillSession({sessionId:'revive',mode:'adventure',selectedCat:cat('base_legendary_02')});var revive=skill.handleSkillTrigger({trigger:'lives_zero',mode:'adventure',gameState:{},selectedCat:cat('base_legendary_02')});assert(revive.activated&&revive.reviveLives===1,'부활 실패');
    return{passed:true,schemaVersion:7,firstReward:first.reward,repeatReward:repeat.reward,starUpgradeReward:stars.reward,packRates:v2.cardPackService.validateCardPackConfig().results,rankedPolicy:v2.skillConfig.rankedTimeAttackPolicy};}
  global.runPhase4Validation=runPhase4Validation;
})(window);
