(function(root,factory){var service=factory();if(typeof module!=='undefined'&&module.exports)module.exports=service;if(root){root.GugudanV2=root.GugudanV2||{};root.GugudanV2.adminBatchGrantService=service;}})(typeof window!=='undefined'?window:null,function(){
  'use strict';
  function uuid(){if(typeof crypto!=='undefined'&&crypto.randomUUID)return crypto.randomUUID();return Array.from({length:4},function(){return Math.floor(Math.random()*0xffffffff).toString(16).padStart(8,'0');}).join('-');}
  function transient(error){return /unavailable|network|timeout|deadline/i.test(String(error&&(error.code||error.message)||''));}
  function createBatch(users,payload,validate){var batchId=uuid(),entries={};users.forEach(function(user){var actionId=uuid();if(validate&&!validate(actionId).valid)throw new Error('invalid_action_id');entries[user.uid]={uid:user.uid,actionId:actionId,status:'pending',attempts:0,user:user};});return {batchId:batchId,resourceType:payload.resourceType,amount:payload.amount,note:payload.note||'',status:'ready',orderedUids:users.map(function(u){return u.uid;}),entries:entries};}
  function retryable(batch){return batch.orderedUids.filter(function(uid){var s=batch.entries[uid].status;return s==='uncertain';});}
  async function run(batch,grant,context,onProgress){if(batch.status==='processing')return batch;batch.status='processing';var queue=batch.orderedUids.filter(function(uid){return batch.entries[uid].status==='pending'||batch.entries[uid].status==='uncertain';}),index=0;async function worker(){while(index<queue.length){var uid=queue[index++],entry=batch.entries[uid];entry.status='processing';entry.attempts++;onProgress&&onProgress(batch,entry);try{var result=await grant({targetUid:uid,grantType:batch.resourceType,amount:batch.amount,note:batch.note,actionId:entry.actionId},context);entry.result=result;entry.before=result.before;entry.after=result.after;entry.status=result.idempotentReplay?'replay':'success';}catch(error){entry.errorCode=error&&(error.code||error.message)||'';entry.errorMessage=String(entry.errorCode);entry.status=transient(error)?'uncertain':'failed';}onProgress&&onProgress(batch,entry);}}await Promise.all(Array.from({length:Math.min(2,queue.length)},worker));var states=Object.keys(batch.entries).map(function(uid){return batch.entries[uid].status;});batch.status=states.some(function(s){return s==='failed'||s==='uncertain';})?'partial':'completed';return batch;}
  return {createBatch:createBatch,run:run,retryable:retryable,transient:transient};
});
