(function(global){
  'use strict';
  var v2=global.GugudanV2=global.GugudanV2||{},database=null,firebaseSdk=null,submitted={},COLLECTION='leaderboardsV3',VERSION='v3';
  function setDatabase(db,sdk){database=db||null;firebaseSdk=sdk||null;}
  function pad(value){return String(value).padStart(2,'0');}
  function kstParts(referenceDate){var date=referenceDate?new Date(referenceDate):new Date(),parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date),values={};parts.forEach(function(part){values[part.type]=part.value;});return{year:Number(values.year),month:Number(values.month),day:Number(values.day)};}
  function getKoreaMonthKey(referenceDate){var value=kstParts(referenceDate);return value.year+'-'+pad(value.month);}
  function getKoreanWeekRange(referenceDate){var value=kstParts(referenceDate),day=new Date(Date.UTC(value.year,value.month-1,value.day)),weekday=day.getUTCDay()||7,thursday=new Date(day);thursday.setUTCDate(day.getUTCDate()+4-weekday);var yearStart=new Date(Date.UTC(thursday.getUTCFullYear(),0,1)),week=Math.ceil((((thursday-yearStart)/86400000)+1)/7),weekKey=thursday.getUTCFullYear()+'-W'+pad(week),monday=new Date(day);monday.setUTCDate(day.getUTCDate()-(weekday-1));return{weekKey:weekKey,label:weekKey,start:monday};}
  function validateScoreSubmission(result){var errors=[];if(!result||result.mode!=='timeAttack')errors.push('지원하지 않는 랭킹 모드');['score','correctCount','wrongCount','totalQuestions','accuracy','bestCombo'].forEach(function(key){if(!Number.isFinite(Number(result&&result[key]))||Number(result[key])<0)errors.push(key+' 값 오류');});if(!result||!result.sessionId)errors.push('세션 ID 누락');if(!result||!String(result.playerId||'').trim())errors.push('playerId 누락');if(!result||!String(result.nickname||'').trim())errors.push('nickname 누락');if(result&&submitted[result.sessionId])errors.push('이미 제출한 세션');return{valid:!errors.length,errors:errors};}
  function better(next,current,field){if(!current)return true;return Number(next[field])>Number(current[field])||(Number(next[field])===Number(current[field])&&(Number(next.correctCount)>Number(current.correctCount)||(Number(next.correctCount)===Number(current.correctCount)&&Number(next.accuracy)>Number(current.accuracy))));}
  function submitScore(result){var validation=validateScoreSubmission(result);if(!validation.valid)return Promise.resolve({ok:false,reason:'validation',errors:validation.errors});if(!database||!firebaseSdk)return Promise.resolve({ok:false,reason:'firebase_unavailable'});submitted[result.sessionId]=true;var playedAt=result.playedAt||new Date().toISOString(),weekKey=getKoreanWeekRange(playedAt).weekKey,playerId=String(result.playerId),base={rankingVersion:VERSION,mode:'timeAttack',nickname:result.nickname,playerId:playerId,score:Number(result.score),correctCount:Number(result.correctCount),accuracy:Number(result.accuracy),wrongCount:Number(result.wrongCount),bestCombo:Number(result.bestCombo),playedAt:playedAt,playedAtTimestamp:firebaseSdk.firestore.FieldValue.serverTimestamp()};var weeklyRef=database.collection(COLLECTION).doc(playerId+'_timeAttack_'+weekKey),allRef=database.collection(COLLECTION).doc(playerId+'_timeAttack_allTimeBest');return database.runTransaction(function(tx){return Promise.all([tx.get(weeklyRef),tx.get(allRef)]).then(function(docs){var weekly=Object.assign({},base,{periodType:'weeklyBest',weekKey:weekKey}),all=Object.assign({},base,{periodType:'allTimeBest'});if(better(weekly,docs[0].exists&&docs[0].data(),'score'))tx.set(weeklyRef,weekly);if(better(all,docs[1].exists&&docs[1].data(),'score'))tx.set(allRef,all);});}).then(function(){return{ok:true,weekKey:weekKey};}).catch(function(error){delete submitted[result.sessionId];console.error('[Ranking write error]',error);return{ok:false,error:error};});}
  function submitOverall(input){if(!database||!firebaseSdk||!input||!input.playerId)return Promise.resolve({ok:false,reason:'firebase_unavailable'});var monthKey=getKoreaMonthKey(input.playedAt),playerId=String(input.playerId),monthlyRef=database.collection(COLLECTION).doc(playerId+'_overall_'+monthKey),allRef=database.collection(COLLECTION).doc(playerId+'_overall_allTime');return database.runTransaction(function(tx){return Promise.all([tx.get(monthlyRef),tx.get(allRef)]).then(function(docs){function value(doc,period){var old=doc.exists?doc.data():{},scoreField=period==='monthly'?'monthlyScore':'totalScore',score=(Number(old[scoreField])||0)+(Number(input.score)||0),correct=(Number(old.correctCount)||0)+(Number(input.correctCount)||0),questions=(Number(old.totalQuestions)||0)+(Number(input.totalQuestions)||0);return{rankingVersion:VERSION,mode:'overall',periodType:period==='monthly'?'monthly':'allTime',monthKey:period==='monthly'?monthKey:null,nickname:input.nickname,playerId:playerId,monthlyScore:period==='monthly'?score:0,totalScore:period==='allTime'?score:0,correctCount:correct,totalQuestions:questions,accuracy:questions?Math.round(correct/questions*10000)/100:0,playedAt:old.playedAt||input.playedAt||new Date().toISOString(),playedAtTimestamp:old.playedAtTimestamp||firebaseSdk.firestore.FieldValue.serverTimestamp()};}tx.set(monthlyRef,value(docs[0],'monthly'));tx.set(allRef,value(docs[1],'allTime'));});}).then(function(){return{ok:true,monthKey:monthKey};}).catch(function(error){console.error('[Overall ranking write error]',error);return{ok:false,error:error};});}
  function indexUrl(error){if(!error||error.code!=='failed-precondition')return null;var match=String(error.message||'').match(/https:\/\/console\.firebase\.google\.com\/[^\s]+/);return match?match[0].replace(/[),.;]+$/,''):null;}
  function queryError(error,fields){console.error('[Ranking query error]',error);console.error('[Required Firestore index fields]',fields.join(' → '));var url=indexUrl(error);if(url)console.error('[Firebase index creation URL]',url);return url;}
  function getLeaderboard(options){options=options||{};var category=options.category==='timeAttack'?'timeAttack':'overall',period=options.period||(category==='timeAttack'?'weeklyBest':'monthly'),field=category==='overall'?(period==='monthly'?'monthlyScore':'totalScore'):'score',fields=['rankingVersion','mode','periodType'];var query=database&&database.collection(COLLECTION).where('rankingVersion','==',VERSION).where('mode','==',category).where('periodType','==',period);if(!query)return Promise.resolve({ok:false,reason:'firebase_unavailable',records:[]});if(category==='overall'&&period==='monthly'){var monthKey=getKoreaMonthKey(options.referenceDate);query=query.where('monthKey','==',monthKey);fields.push('monthKey');}if(category==='timeAttack'&&period==='weeklyBest'){var weekKey=getKoreanWeekRange(options.referenceDate).weekKey;query=query.where('weekKey','==',weekKey);fields.push('weekKey');}fields.push(field+' desc','correctCount desc','accuracy desc','playedAtTimestamp asc');query=query.orderBy(field,'desc').orderBy('correctCount','desc').orderBy('accuracy','desc').orderBy('playedAtTimestamp','asc').limit(10);return query.get().then(function(snapshot){return{ok:true,records:snapshot.docs.map(function(doc){var data=doc.data();data.id=doc.id;data.displayScore=Number(data[field])||0;return data;})};}).catch(function(error){return{ok:false,records:[],error:error,indexUrl:queryError(error,fields)};});}
  function getPlayerRecord(options){options=options||{};if(!database||!options.playerId)return Promise.resolve(null);var category=options.category==='timeAttack'?'timeAttack':'overall',period=options.period||(category==='timeAttack'?'weeklyBest':'monthly'),id=String(options.playerId);if(category==='overall')id+='_overall_'+(period==='monthly'?getKoreaMonthKey(options.referenceDate):'allTime');else id+='_timeAttack_'+(period==='weeklyBest'?getKoreanWeekRange(options.referenceDate).weekKey:'allTimeBest');return database.collection(COLLECTION).doc(id).get().then(function(doc){if(!doc.exists)return null;var data=doc.data(),field=category==='overall'?(period==='monthly'?'monthlyScore':'totalScore'):'score';data.id=doc.id;data.displayScore=Number(data[field])||0;return data;}).catch(function(error){console.error('[Player ranking query error]',error);return null;});}
  function alias(category,period,options){options=options||{};return getLeaderboard(Object.assign({},options,{category:category,period:period}));}
  v2.rankingService={LEADERBOARD_VERSION:VERSION,collectionName:COLLECTION,allowedModes:['overall','timeAttack'],setDatabase:setDatabase,getKoreanWeekRange:getKoreanWeekRange,getKoreaMonthKey:getKoreaMonthKey,getIndexCreationUrl:indexUrl,validateScoreSubmission:validateScoreSubmission,submitScore:submitScore,submitOverall:submitOverall,getLeaderboard:getLeaderboard,getPlayerRecord:getPlayerRecord,getMonthlyRanking:function(o){return alias('overall','monthly',o);},getAllTimeRanking:function(o){return alias(o&&o.mode==='timeAttack'?'timeAttack':'overall',o&&o.mode==='timeAttack'?'allTimeBest':'allTime',o);},getWeeklyRanking:function(o){return alias('timeAttack','weeklyBest',o);}};
})(window);
