(function (global) {
  'use strict';
  var v2=global.GugudanV2;
  function zero(){return{coins:0,normalTickets:0,premiumTickets:0,starCoins:0};}
  function validateRewardConfig(config){var errors=[];['normalFirstClear','normalRepeatClear','midBossFirstClear','finalBossFirstClear'].forEach(function(key){var reward=config&&config[key];['coins','normalTickets','premiumTickets'].forEach(function(field){if(!reward||!Number.isInteger(reward[field])||reward[field]<0)errors.push(key+'.'+field);});});[1,2,3].forEach(function(star){if(!config.starMilestones||!Number.isInteger(config.starMilestones[star])||config.starMilestones[star]<0)errors.push('starMilestones.'+star);});return{valid:!errors.length,errors:errors};}
  function calculateStageRewards(input){var result=zero(),stage=input.stage,cleared=Boolean(input.cleared),first=Boolean(input.isFirstClear),previous=Math.max(0,Number(input.previousStars)||0),current=Math.max(previous,Number(input.currentStars)||0);if(!cleared)return Object.assign(result,{firstClear:false,label:'도전 실패'});var key=first?(stage.type==='midBoss'?'midBossFirstClear':stage.type==='boss'?'finalBossFirstClear':'normalFirstClear'):'normalRepeatClear',base=v2.rewardConfig[key];result.coins=base.coins;result.normalTickets=base.normalTickets;result.premiumTickets=base.premiumTickets;for(var star=previous+1;star<=current;star+=1)result.starCoins+=v2.rewardConfig.starMilestones[star]||0;result.coins+=result.starCoins;result.firstClear=first;result.label=first?'최초 클리어 보상':'반복 클리어 보상';return result;}
  function claimStageRewards(input){var save=v2.storageService.loadSaveData(),history=save.rewardHistory,sessionId=String(input.sessionId||'');if(!sessionId)return{ok:false,reason:'missing_session',reward:zero()};if(history.rewardedSessionIds.indexOf(sessionId)>=0)return{ok:false,reason:'already_claimed',reward:zero()};var first=history.firstClearStageIds.indexOf(input.stage.id)<0,previous=Number(history.rewardedStarMilestones[input.stage.id]||0),reward=calculateStageRewards({stage:input.stage,cleared:input.cleared,isFirstClear:first,previousStars:previous,currentStars:input.stars});if(!input.cleared)return{ok:false,reason:'not_cleared',reward:reward};save.currency.coins+=reward.coins;save.currency.normalTickets+=reward.normalTickets;save.currency.premiumTickets+=reward.premiumTickets;history.rewardedSessionIds.push(sessionId);history.rewardedSessionIds=history.rewardedSessionIds.slice(-v2.rewardConfig.rewardedSessionLimit);if(first)history.firstClearStageIds.push(input.stage.id);history.rewardedStarMilestones[input.stage.id]=Math.max(previous,input.stars||0);if(!v2.storageService.saveSaveData(save))return{ok:false,reason:'save_failed',reward:zero()};return{ok:true,reward:reward,currency:save.currency};}
  v2.rewardService={validateRewardConfig:validateRewardConfig,calculateStageRewards:calculateStageRewards,claimStageRewards:claimStageRewards};
})(window);
