(function (global) {
  'use strict';
  var v2=global.GugudanV2,session=null;
  function empty(){return{sessionId:null,mode:null,selectedCatId:null,activeSkillId:null,activationCount:0,consumed:false,manualSkillAvailable:false,triggeredCombos:[],isRankedRun:false};}
  function initializeSkillSession(input){var cat=input.selectedCat||null;session=empty();session.sessionId=input.sessionId;session.mode=input.mode;session.selectedCatId=cat&&cat.id;session.activeSkillId=cat&&cat.skill&&cat.skill.id;session.manualSkillAvailable=session.activeSkillId==='remove_wrong_option';session.isRankedRun=Boolean(input.isRankedRun);return getSession();}
  function definition(skillId){return v2.skillConfig.skills[skillId]||null;}
  function canActivateSkill(input){var skill=input.skill||null,def=skill&&definition(skill.id);if(!v2.skillConfig.enabled||!skill||!def||!def.enabled||!session||session.consumed)return false;if(def.modes.indexOf(input.mode)<0)return false;if(input.mode==='timeAttack'&&input.gameState&&input.gameState.isRankedRun&&!def.cosmetic)return false;return true;}
  function activateSkill(input){if(!canActivateSkill(input))return{activated:false};session.activationCount+=1;var id=input.skill.id;if(id==='combo_special_meow'||id==='season_moon_meow'){var combo=input.gameState.combo;if(!combo||combo%10||session.triggeredCombos.indexOf(combo)>=0)return{activated:false};session.triggeredCombos.push(combo);return{activated:true,effect:'lightning',message:'번개의 야옹!'};}if(id==='first_mistake_guard'){session.consumed=true;return{activated:true,preventLifeLoss:true,resetCombo:v2.skillConfig.shieldResetsCombo,effect:'shield',message:'냥냥 실드!'};}if(id==='remove_wrong_option'){if(!session.manualSkillAvailable||input.gameState.inputLocked||input.gameState.optionCount<=3)return{activated:false};session.consumed=true;session.manualSkillAvailable=false;return{activated:true,removeWrongOption:true,effect:'wisdom',message:'지혜의 발톱!'};}if(id==='time_bonus'){session.consumed=true;return{activated:true,bonusSeconds:defSeconds(id),effect:'time',message:'시간 +'+defSeconds(id)+'초'};}if(id==='legendary_boss_roar'||id==='season_blue_moon_roar'){session.consumed=true;return{activated:true,effect:'gold',message:'황금의 포효!'};}if(id==='single_revive'){session.consumed=true;return{activated:true,reviveLives:defRevive(id),effect:'revive',message:'아홉 번째 기회!'};}return{activated:false};}
  function defSeconds(id){return Number(definition(id).seconds)||2;}function defRevive(id){return Number(definition(id).reviveLives)||1;}
  function handleSkillTrigger(input){var cat=input.selectedCat;if(!cat||!cat.skill)return{activated:false};var id=cat.skill.id,trigger=input.trigger;if((id==='combo_special_meow'||id==='season_moon_meow')&&trigger==='combo')return activateSkill({skill:cat.skill,mode:input.mode,gameState:input.gameState});if(id==='first_mistake_guard'&&trigger==='wrong')return activateSkill({skill:cat.skill,mode:input.mode,gameState:input.gameState});if(id==='time_bonus'&&trigger==='timed_start')return activateSkill({skill:cat.skill,mode:input.mode,gameState:input.gameState});if((id==='legendary_boss_roar'||id==='season_blue_moon_roar')&&trigger==='boss_start')return activateSkill({skill:cat.skill,mode:input.mode,gameState:input.gameState});if(id==='single_revive'&&trigger==='lives_zero')return activateSkill({skill:cat.skill,mode:input.mode,gameState:input.gameState});return{activated:false};}
  function getSession(){return JSON.parse(JSON.stringify(session||empty()));}function resetSkillSession(){session=empty();return getSession();}
  function validateSkillSession(value){value=value||session;var errors=[];if(!value||!Array.isArray(value.triggeredCombos))errors.push('triggeredCombos');if(value&&value.activationCount<0)errors.push('activationCount');return{valid:!errors.length,errors:errors};}
  function validateCatSkillData(){var errors=[],allowed=['sound_effect','mistake_guard','remove_option','time_bonus','boss_effect','revive'];(v2.baseCats||[]).forEach(function(cat){if((cat.rarity==='normal'||cat.rarity==='rare')&&cat.skill)errors.push(cat.id);if((cat.rarity==='hero'||cat.rarity==='legendary')&&(!cat.skill||allowed.indexOf(cat.skill.type)<0))errors.push(cat.id);});return{valid:!errors.length,errors:errors};}
  v2.skillEngine={initializeSkillSession:initializeSkillSession,canActivateSkill:canActivateSkill,activateSkill:activateSkill,handleSkillTrigger:handleSkillTrigger,resetSkillSession:resetSkillSession,getSession:getSession,validateSkillSession:validateSkillSession,validateCatSkillData:validateCatSkillData};
})(window);
